PATCH /api/2.3/tenders/4506e1c848de480abc345cd2b9d24856/contracts/c83c52eebeb04e3b8491cd83cc0e2d1f?acc_token=6e631cfeb801444e929b7f3ba2373f60 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "additionalAwardIDs": [
      "32320cc41d1a413f9824eacf1d97747a"
    ], 
    "items": [
      {
        "relatedLot": "e2f2e61d734248b1b1d98e47fa80eae4", 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-11-11T15:09:39.262050+02:00", 
          "endDate": "2016-11-14T15:09:39.262050+02:00"
        }, 
        "id": "e1d33fdf53984f28a0743538fec8f491", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateSigned": "2016-11-09T17:09:44.276459+02:00", 
    "date": "2016-11-09T17:09:44.281524+02:00", 
    "awardID": "87d6618a7c0e430eba4664b0bdb058c6", 
    "id": "c83c52eebeb04e3b8491cd83cc0e2d1f", 
    "contractID": "UA-2016-11-09-000001-1"
  }
}

