PATCH /api/2.3/tenders/f448b78835e64a9599566e5e305daf9f/bids/419e5bf6f28847a8826f3b61bae86340?acc_token=b829fcfa49424cf5a820c9de3217a740 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "value": {
      "amount": 400
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/f448b78835e64a9599566e5e305daf9f/bids/419e5bf6f28847a8826f3b61bae86340/documents/fb89e8af02e243e2a2cb8a35dabb151b?download=beea1fa45f764317a054b52a3615c86f", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-03-03T15:50:00.732548+02:00", 
        "id": "fb89e8af02e243e2a2cb8a35dabb151b", 
        "dateModified": "2017-03-03T15:50:00.732582+02:00"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 400.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "date": "2017-03-03T15:50:00.802612+02:00", 
    "id": "419e5bf6f28847a8826f3b61bae86340"
  }
}

