PATCH /api/2.0/tenders/d14225f722384c46a31b4e4470b66d8d/awards/e7b49c9e3f1548368349951d2efbaec8?acc_token=ef78f3436aaa4ce8a6b33760c419db75 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "complaintPeriod": {
      "startDate": "2016-03-16T17:54:17.540154+02:00", 
      "endDate": "2016-03-17T17:54:17.895484+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "bb6715d1cc0e499eb0c7e5fb84f95d06", 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-03-16T17:54:17.540437+02:00", 
    "id": "e7b49c9e3f1548368349951d2efbaec8"
  }
}

