GET /api/2.3/tenders/fdc75be18cf448aa828b4e28cd617a1b/awards/28e7c39d1b7148c2ae8063e14f31b1d2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "complaintPeriod": {
      "startDate": "2016-07-20T17:17:23.337962+03:00", 
      "endDate": "2016-07-22T17:17:23.683167+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "62ce810351d74e7d8145189aa1ed7151", 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-07-20T17:17:23.683131+03:00", 
    "id": "28e7c39d1b7148c2ae8063e14f31b1d2"
  }
}

