PATCH /api/2.3/tenders/b5f0fd0ef8684ba997e3cd344fd1d131/awards/18cac3d0e313416aa3cebbff0a0ab41c?acc_token=41f50461be174ae1bee022aefeeb1744 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "cancelled"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/b5f0fd0ef8684ba997e3cd344fd1d131/awards/9264560bc5aa40ca99bf825e6e9eb48d

{
  "data": {
    "status": "cancelled", 
    "complaintPeriod": {
      "startDate": "2017-06-24T18:05:39.073951+03:00", 
      "endDate": "2017-06-24T18:05:39.605379+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ],
    "bid_id": "a8e1478a504347999d3e005839e74bfb",
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    },
    "date": "2017-06-24T18:05:39.620302+03:00", 
    "id": "18cac3d0e313416aa3cebbff0a0ab41c"
  }
}

