GET /api/0.12/tenders/6e4678dd3a8749d1b16741168a8e3506/awards/4e09f650eef44d5d9260d9fc0bbeb9d9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "complaintPeriod": {
      "startDate": "2016-03-18T15:00:23.813235+02:00", 
      "endDate": "2016-03-19T15:00:24.365363+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "9ed5b19b5d7249e6b73c2fb7ed62dad2", 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-03-18T15:00:23.815550+02:00", 
    "id": "4e09f650eef44d5d9260d9fc0bbeb9d9"
  }
}

