PATCH /api/2.3/tenders/81a0e2e3a6134c28bf7e1e1e128be4ec/awards/c77c51eb4dd24069984c68550de429c6?acc_token=abc1c96db40e41d8925d8cb3de9e8eb9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "cancelled"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/81a0e2e3a6134c28bf7e1e1e128be4ec/awards/a3d50b7e11314c2295552797db239598

{
  "data": {
    "status": "cancelled", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "Unsuccessful_Reason.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/21db828fbcac4af6a8e78f9b8e975349?KeyID=425d5e40&Signature=B0i8EtxBIOLbNyXR7UlomzkPitHLHC4g1PzIufwuij%252BuZ2ugYKGTP7iFo274pbIgxy6L89CDM5o2JSsh9uK7Dw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-07-25T17:49:18.589499+03:00", 
        "id": "75184b8e0f604855b8344fa04a60a765", 
        "dateModified": "2017-07-25T17:49:18.589517+03:00"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2017-07-25T17:49:18.471612+03:00", 
      "endDate": "2017-07-25T17:49:21.922214+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "bid_id": "e488090f1b484f378b8507de43a34507", 
    "value": {
      "currency": "UAH", 
      "amount": 450.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-07-25T17:49:21.930993+03:00", 
    "complaints": [
      {
        "status": "resolved", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "complaint_owner", 
            "title": "Complaint_Attachement.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/086ffbb6451e4e0293d428c582e270dd?KeyID=425d5e40&Signature=8V1k1s4GmLETaZYL%2FTJQw%2F8n26c4g%2FhtNMOMV%252BsMSw40m3QgIIoz8m2MRUPes%252BDL0d88uqhfywaVws3KDsurCQ%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2017-07-25T17:49:19.743173+03:00", 
            "id": "f8e700620cdf44098a0ec69e8afb4030", 
            "dateModified": "2017-07-25T17:49:19.743203+03:00"
          }
        ], 
        "description": "complaint description", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "resolved", 
        "type": "claim", 
        "title": "complaint title", 
        "satisfied": true, 
        "tendererAction": "Виправлено неконкурентні умови", 
        "dateAnswered": "2017-07-25T17:49:20.407127+03:00", 
        "tendererActionDate": "2017-07-25T17:49:20.407142+03:00", 
        "dateSubmitted": "2017-07-25T17:49:19.977271+03:00", 
        "complaintID": "UA-2017-07-25-000001.5", 
        "date": "2017-07-25T17:49:20.548694+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "f2b1bdd5f6134a41a6e4538602d43101"
      }, 
      {
        "status": "resolved", 
        "description": "complaint description", 
        "title": "complaint title", 
        "resolutionType": "resolved", 
        "type": "claim", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "satisfied": false, 
        "dateAnswered": "2017-07-25T17:49:20.671179+03:00", 
        "dateSubmitted": "2017-07-25T17:49:20.177778+03:00", 
        "complaintID": "UA-2017-07-25-000001.6", 
        "date": "2017-07-25T17:49:20.812424+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "ff0c2c3b05304a5c81e6275d69326793"
      }, 
      {
        "status": "resolved", 
        "description": "complaint description", 
        "title": "complaint title", 
        "resolutionType": "resolved", 
        "type": "claim", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "satisfied": false, 
        "dateAnswered": "2017-07-25T17:49:21.079037+03:00", 
        "dateSubmitted": "2017-07-25T17:49:20.941030+03:00", 
        "complaintID": "UA-2017-07-25-000001.7", 
        "date": "2017-07-25T17:49:21.221558+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "92703cd97d9a4dd487c91081cda33ee9"
      }, 
      {
        "status": "resolved", 
        "description": "complaint description", 
        "title": "complaint title", 
        "resolutionType": "resolved", 
        "type": "claim", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "satisfied": false, 
        "dateAnswered": "2017-07-25T17:49:21.514310+03:00", 
        "dateSubmitted": "2017-07-25T17:49:21.353246+03:00", 
        "complaintID": "UA-2017-07-25-000001.8", 
        "date": "2017-07-25T17:49:21.676608+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "b01b392483224877b91cc74568084ce3"
      }
    ], 
    "id": "c77c51eb4dd24069984c68550de429c6"
  }
}

