PATCH /api/2.3/tenders/8c7840a135e342abb80894985f570f06/awards/6cb65764e32c4ef5a3c8818bafa8b6ba?acc_token=cb1f23460fc94939a34007cdd52598cf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "complaintPeriod": {
      "startDate": "2016-07-21T17:14:40.280308+03:00", 
      "endDate": "2016-07-25T17:14:40.627368+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "3a06a3598e6c47179281d843e0f95a64", 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-07-21T17:14:40.627332+03:00", 
    "id": "6cb65764e32c4ef5a3c8818bafa8b6ba"
  }
}

