GET /api/2.3/tenders/8c7840a135e342abb80894985f570f06/awards HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "unsuccessful", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "Unsuccessful_Reason.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/47487c5a75174965b639729223239b61?KeyID=9d50f426&Signature=0ACwOEehd7lO1Urq6iQX8nF4wXlFpEWHLpnPfnzoYgW2Rg7lgBGIJ5kGRxmhHKomAmFEbUubxNKOWE%252BKBHAmBDQAAAA3AAAANAAAADgAAAA3AAAAYwAAADUAAABhAAAA", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-07-21T17:14:40.018144+03:00", 
          "id": "1c8010d304e9415baa9ddc3c378ad154", 
          "dateModified": "2016-07-21T17:14:40.018174+03:00"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2016-07-21T17:14:39.753797+03:00", 
        "endDate": "2016-07-25T17:14:40.279333+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "afe31fef22b4405cb977030cbfd9be57", 
      "value": {
        "currency": "UAH", 
        "amount": 450.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-07-21T17:14:40.279292+03:00", 
      "complaints": [
        {
          "status": "resolved", 
          "documents": [
            {
              "hash": "md5:00000000000000000000000000000000", 
              "author": "complaint_owner", 
              "title": "Complaint_Attachement.pdf", 
              "url": "http://public.docs-sandbox.openprocurement.org/get/9bb44b4e53df423c91366f60e1ec84e2?KeyID=9d50f426&Signature=NlJ9xMajG%2FjBKtSh1C0um%252BYfq6%2FNUGHc3bBAv3%2FijWu1zkw58Zrm53Uqm5AT%252BZ7jWTovn%252BvKWQFPVNASnYxtCTkAAABiAAAAYgAAADQAAAA0AAAAYgAAADQAAABlAAAA", 
              "format": "application/pdf", 
              "documentOf": "tender", 
              "datePublished": "2016-07-21T17:14:42.145284+03:00", 
              "id": "ed9b23275c3d4375a1f550d986387008", 
              "dateModified": "2016-07-21T17:14:42.145327+03:00"
            }
          ], 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "claim", 
          "title": "complaint title", 
          "satisfied": true, 
          "tendererAction": "Виправлено неконкурентні умови", 
          "dateAnswered": "2016-07-21T17:14:43.218560+03:00", 
          "tendererActionDate": "2016-07-21T17:14:43.218588+03:00", 
          "dateSubmitted": "2016-07-21T17:14:42.445458+03:00", 
          "complaintID": "UA-2016-07-21-000001.5", 
          "date": "2016-07-21T17:14:41.819478+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "152df6bf4df0461e953ea0ed96319858"
        }, 
        {
          "status": "invalid", 
          "dateDecision": "2016-07-21T17:14:44.530721+03:00", 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "complaint", 
          "title": "complaint title", 
          "satisfied": false, 
          "dateEscalated": "2016-07-21T17:14:44.173585+03:00", 
          "dateAnswered": "2016-07-21T17:14:43.846527+03:00", 
          "dateSubmitted": "2016-07-21T17:14:42.737568+03:00", 
          "complaintID": "UA-2016-07-21-000001.6", 
          "date": "2016-07-21T17:14:42.736071+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "2f5e4b096414493c9c60514dcac5a087"
        }, 
        {
          "status": "resolved", 
          "dateDecision": "2016-07-21T17:14:47.159319+03:00", 
          "documents": [
            {
              "hash": "md5:00000000000000000000000000000000", 
              "author": "reviewers", 
              "title": "ComplaintResolution.pdf", 
              "url": "http://public.docs-sandbox.openprocurement.org/get/2556a45a3df94fe784363dbaac50743b?KeyID=9d50f426&Signature=vS8zZVaOnLIgDgjooQlBTtnSr%2F9xjFe76oPevnvocz8QBB%252Bdf3ljsP%2FmlA%2FyyDHX%252Bft9ObY0wCVDTdKKbspzBjIAAAA1AAAANQAAADYAAABhAAAANAAAADUAAABhAAAA", 
              "format": "application/pdf", 
              "documentOf": "tender", 
              "datePublished": "2016-07-21T17:14:46.810575+03:00", 
              "id": "13f4f7d9172243b5a2903243419099b3", 
              "dateModified": "2016-07-21T17:14:46.810606+03:00"
            }
          ], 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "complaint", 
          "title": "complaint title", 
          "satisfied": false, 
          "dateEscalated": "2016-07-21T17:14:45.468978+03:00", 
          "dateAnswered": "2016-07-21T17:14:45.149922+03:00", 
          "dateSubmitted": "2016-07-21T17:14:44.830072+03:00", 
          "complaintID": "UA-2016-07-21-000001.7", 
          "date": "2016-07-21T17:14:44.828567+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "1e8f2fae79e34a429977978e76765005"
        }, 
        {
          "status": "declined", 
          "dateDecision": "2016-07-21T17:14:47.522714+03:00", 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "complaint", 
          "title": "complaint title", 
          "satisfied": false, 
          "dateEscalated": "2016-07-21T17:14:46.485769+03:00", 
          "dateAnswered": "2016-07-21T17:14:46.144563+03:00", 
          "dateSubmitted": "2016-07-21T17:14:45.797831+03:00", 
          "complaintID": "UA-2016-07-21-000001.8", 
          "date": "2016-07-21T17:14:45.795841+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "b8b76757989e40dea42db72149b8ad59"
        }
      ], 
      "id": "5ed2003616f640bd8c0dbc037567908f"
    }, 
    {
      "status": "cancelled", 
      "complaintPeriod": {
        "startDate": "2016-07-21T17:14:40.280308+03:00", 
        "endDate": "2016-07-21T17:14:40.963084+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "3a06a3598e6c47179281d843e0f95a64", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-07-21T17:14:40.963049+03:00", 
      "id": "6cb65764e32c4ef5a3c8818bafa8b6ba"
    }, 
    {
      "status": "unsuccessful", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "title": "Cancellation_Reason.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/1a97d710c5e94114a330f2299550008a?KeyID=9d50f426&Signature=F2oc4WvTTEoAs6JEb1P6ySujTIFxw%2F7mL5kZJo5j6Rm%252Bo%252BO2NGybNROTz6v%2FQSIBJ4CIvFDZrWS2VbD%2FR8DDCTEAAABhAAAAOQAAADcAAABkAAAANwAAADEAAAAwAAAA", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-07-21T17:14:41.313976+03:00", 
          "id": "cf8ac5c906e3498384be5618bd9fcb1a", 
          "dateModified": "2016-07-21T17:14:41.314008+03:00"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2016-07-21T17:14:40.963770+03:00", 
        "endDate": "2016-07-25T17:14:41.563330+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "3a06a3598e6c47179281d843e0f95a64", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-07-21T17:14:41.563302+03:00", 
      "id": "be4cb0e0affc4d71a4f1bf64d5311bc9"
    }, 
    {
      "status": "pending", 
      "complaintPeriod": {
        "startDate": "2016-07-21T17:14:41.564065+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "441f09bcacca4fcf876e0e1886cebc86", 
      "value": {
        "currency": "UAH", 
        "amount": 475.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-07-21T17:14:41.564325+03:00", 
      "id": "6dcc0fa176c5455db5973077862b2461"
    }
  ]
}

