GET /api/2.3/tenders/6fb28391664b4e31b9002882b4d67573/awards HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "pending", 
      "complaintPeriod": {
        "startDate": "2017-06-24T18:00:29.896879+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "78fd62edb0ef44bf8de3477f3b24cce3", 
      "value": {
        "currency": "UAH", 
        "amount": 450.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2017-06-24T18:00:29.896860+03:00", 
      "id": "04f866d1fc3f4a14b463846b048a8a4e"
    }
  ]
}

