PATCH /api/0.12/tenders/6e4678dd3a8749d1b16741168a8e3506/awards/14f73b05ed124d5e8bc190f9f8247083?acc_token=296f26fc7d144d99875136e1555f510f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "unsuccessful"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/0.12/tenders/6e4678dd3a8749d1b16741168a8e3506/awards/09f165a7193c4ebc94b6abbf6d1ab50c

{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "title": "Cancellation_Reason.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/6e4678dd3a8749d1b16741168a8e3506/awards/14f73b05ed124d5e8bc190f9f8247083/documents/e050887ef03944ceac5b397d28370191?download=b82210e1d8f04f608f23098e933bb1b9", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-18T15:00:25.295583+02:00", 
        "id": "e050887ef03944ceac5b397d28370191", 
        "dateModified": "2016-03-18T15:00:25.295621+02:00"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2016-03-18T15:00:24.898913+02:00", 
      "endDate": "2016-03-19T15:00:25.561422+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "9ed5b19b5d7249e6b73c2fb7ed62dad2", 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-03-18T15:00:24.899344+02:00", 
    "id": "14f73b05ed124d5e8bc190f9f8247083"
  }
}

