GET /api/2.0/tenders/df482adf4b1a41d38ff9d7f1fd8888c3/awards?acc_token=c53e53a0e11c486ba2e3675edfb19d28 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "cancelled", 
      "documents": [
        {
          "title": "Unsuccessful_Reason.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/df482adf4b1a41d38ff9d7f1fd8888c3/awards/c53e53a0e11c486ba2e3675edfb19d28/documents/1ca364304e4643128240f1ee064315fe?download=561b5c137ed04e07819d0f8a2e34af2f", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-03-16T11:22:17.916002+02:00", 
          "id": "1ca364304e4643128240f1ee064315fe", 
          "dateModified": "2016-03-16T11:22:17.916041+02:00"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2016-03-16T11:22:17.587663+02:00", 
        "endDate": "2016-03-16T11:22:26.767660+02:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "cad36285c65b4fa6b26fd4c3de64b61e", 
      "value": {
        "currency": "UAH", 
        "amount": 450.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-03-16T11:22:17.588009+02:00", 
      "complaints": [
        {
          "status": "resolved", 
          "documents": [
            {
              "author": "complaint_owner", 
              "title": "Complaint_Attachement.pdf", 
              "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/df482adf4b1a41d38ff9d7f1fd8888c3/awards/c53e53a0e11c486ba2e3675edfb19d28/complaints/26a86a7e7887444db3c4cc1a9ce384b7/documents/480c607f36ba4a8495663b34af597f6b?download=2d396ecceb1640308f5c66364c9350f8", 
              "format": "application/pdf", 
              "documentOf": "tender", 
              "datePublished": "2016-03-16T11:22:20.207949+02:00", 
              "id": "480c607f36ba4a8495663b34af597f6b", 
              "dateModified": "2016-03-16T11:22:20.207988+02:00"
            }
          ], 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "claim", 
          "title": "complaint title", 
          "satisfied": true, 
          "tendererAction": "Виправлено неконкурентні умови", 
          "dateAnswered": "2016-03-16T11:22:21.480153+02:00", 
          "tendererActionDate": "2016-03-16T11:22:21.480175+02:00", 
          "dateSubmitted": "2016-03-16T11:22:20.553772+02:00", 
          "complaintID": "UA-2016-03-16-000001.5", 
          "date": "2016-03-16T11:22:19.883796+02:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "26a86a7e7887444db3c4cc1a9ce384b7"
        }, 
        {
          "status": "invalid", 
          "dateDecision": "2016-03-16T11:22:22.908941+02:00", 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "claim", 
          "title": "complaint title", 
          "satisfied": false, 
          "dateEscalated": "2016-03-16T11:22:22.583444+02:00", 
          "dateAnswered": "2016-03-16T11:22:22.183275+02:00", 
          "dateSubmitted": "2016-03-16T11:22:20.979325+02:00", 
          "complaintID": "UA-2016-03-16-000001.6", 
          "date": "2016-03-16T11:22:20.977962+02:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "acef0f8bd37e47348cee6814eafc033c"
        }, 
        {
          "status": "resolved", 
          "dateDecision": "2016-03-16T11:22:25.843967+02:00", 
          "documents": [
            {
              "author": "reviewers", 
              "title": "ComplaintResolution.pdf", 
              "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/df482adf4b1a41d38ff9d7f1fd8888c3/awards/c53e53a0e11c486ba2e3675edfb19d28/complaints/836ff94031354bc3aba2f7a69391f4da/documents/95847a5ea70346b78de5f7719e1ec352?download=c28281028104439da46b2e7da1aafe10", 
              "format": "application/pdf", 
              "documentOf": "tender", 
              "datePublished": "2016-03-16T11:22:25.458437+02:00", 
              "id": "95847a5ea70346b78de5f7719e1ec352", 
              "dateModified": "2016-03-16T11:22:25.458475+02:00"
            }
          ], 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "claim", 
          "title": "complaint title", 
          "satisfied": false, 
          "dateEscalated": "2016-03-16T11:22:23.977784+02:00", 
          "dateAnswered": "2016-03-16T11:22:23.618508+02:00", 
          "dateSubmitted": "2016-03-16T11:22:23.261189+02:00", 
          "complaintID": "UA-2016-03-16-000001.7", 
          "date": "2016-03-16T11:22:23.259817+02:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "836ff94031354bc3aba2f7a69391f4da"
        }, 
        {
          "status": "declined", 
          "dateDecision": "2016-03-16T11:22:26.220076+02:00", 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "claim", 
          "title": "complaint title", 
          "satisfied": false, 
          "dateEscalated": "2016-03-16T11:22:25.086165+02:00", 
          "dateAnswered": "2016-03-16T11:22:24.712440+02:00", 
          "dateSubmitted": "2016-03-16T11:22:24.346069+02:00", 
          "complaintID": "UA-2016-03-16-000001.8", 
          "date": "2016-03-16T11:22:24.344681+02:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "203c4206f8aa4dacb286d50b85b19c39"
        }
      ], 
      "id": "c53e53a0e11c486ba2e3675edfb19d28"
    }, 
    {
      "status": "cancelled", 
      "complaintPeriod": {
        "startDate": "2016-03-16T11:22:18.182710+02:00", 
        "endDate": "2016-03-16T11:22:26.767660+02:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "5dc348584900483787120ac8586670da", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-03-16T11:22:18.183029+02:00", 
      "id": "828d3e512cb2406f901f450c50e943b2"
    }, 
    {
      "status": "cancelled", 
      "documents": [
        {
          "title": "Cancellation_Reason.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/df482adf4b1a41d38ff9d7f1fd8888c3/awards/d4cb44fd51aa49a4860b9dbc21e7e954/documents/4a6bab918ba746499b7969f74e52b11b?download=ca096b8719bd4d70be7107349fa6a8ea", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-03-16T11:22:19.260884+02:00", 
          "id": "4a6bab918ba746499b7969f74e52b11b", 
          "dateModified": "2016-03-16T11:22:19.260923+02:00"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2016-03-16T11:22:18.873516+02:00", 
        "endDate": "2016-03-16T11:22:26.767660+02:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "5dc348584900483787120ac8586670da", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-03-16T11:22:18.873859+02:00", 
      "id": "d4cb44fd51aa49a4860b9dbc21e7e954"
    }, 
    {
      "status": "cancelled", 
      "complaintPeriod": {
        "startDate": "2016-03-16T11:22:19.580556+02:00", 
        "endDate": "2016-03-16T11:22:26.767660+02:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "b5a9aa92df9749c48bd3b2fda36643c4", 
      "value": {
        "currency": "UAH", 
        "amount": 475.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-03-16T11:22:19.580873+02:00", 
      "id": "b90b127498c045a98eb22c4ea683abf7"
    }, 
    {
      "status": "pending", 
      "complaintPeriod": {
        "startDate": "2016-03-16T11:22:26.768435+02:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "cad36285c65b4fa6b26fd4c3de64b61e", 
      "value": {
        "currency": "UAH", 
        "amount": 450.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-03-16T11:22:26.768762+02:00", 
      "id": "5fb6b516b40144c39e86f84353d79d82"
    }
  ]
}

