GET /api/2.0/tenders/9098e60f7f804155b50899f6feea3b92/awards?acc_token=3ac4201038a7447e8ed75b11dc6b311e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "unsuccessful", 
      "documents": [
        {
          "title": "Unsuccessful_Reason.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/9098e60f7f804155b50899f6feea3b92/awards/3ac4201038a7447e8ed75b11dc6b311e/documents/16c448bd28dc49d5860e9a42d8a21cb8?download=1196a2ae52594d34b2fd584d4689d92f", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-03-16T14:11:48.393652+02:00", 
          "id": "16c448bd28dc49d5860e9a42d8a21cb8", 
          "dateModified": "2016-03-16T14:11:48.393691+02:00"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2016-03-16T14:11:48.044026+02:00", 
        "endDate": "2016-03-17T14:11:48.666805+02:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "86a00452e8234ec3b96d73e41ef5f2f3", 
      "value": {
        "currency": "UAH", 
        "amount": 450.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-03-16T14:11:48.044361+02:00", 
      "complaints": [
        {
          "status": "resolved", 
          "documents": [
            {
              "author": "complaint_owner", 
              "title": "Complaint_Attachement.pdf", 
              "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/9098e60f7f804155b50899f6feea3b92/awards/3ac4201038a7447e8ed75b11dc6b311e/complaints/1c20f274081043809860d1ce070bdb0a/documents/da7eda23a733493eaee8ca8eeda897ef?download=e535f081c24d4df291decf3c69cd3530", 
              "format": "application/pdf", 
              "documentOf": "tender", 
              "datePublished": "2016-03-16T14:11:50.799265+02:00", 
              "id": "da7eda23a733493eaee8ca8eeda897ef", 
              "dateModified": "2016-03-16T14:11:50.799303+02:00"
            }
          ], 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "claim", 
          "title": "complaint title", 
          "satisfied": true, 
          "tendererAction": "Виправлено неконкурентні умови", 
          "dateAnswered": "2016-03-16T14:11:52.007274+02:00", 
          "tendererActionDate": "2016-03-16T14:11:52.007297+02:00", 
          "dateSubmitted": "2016-03-16T14:11:51.134452+02:00", 
          "complaintID": "UA-2016-03-16-000001.5", 
          "date": "2016-03-16T14:11:50.470674+02:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "1c20f274081043809860d1ce070bdb0a"
        }, 
        {
          "status": "invalid", 
          "dateDecision": "2016-03-16T14:11:53.515675+02:00", 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "claim", 
          "title": "complaint title", 
          "satisfied": false, 
          "dateEscalated": "2016-03-16T14:11:53.121273+02:00", 
          "dateAnswered": "2016-03-16T14:11:52.713013+02:00", 
          "dateSubmitted": "2016-03-16T14:11:51.484291+02:00", 
          "complaintID": "UA-2016-03-16-000001.6", 
          "date": "2016-03-16T14:11:51.482928+02:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "f8c244e946c44fa59fa09dafecc20e49"
        }, 
        {
          "status": "resolved", 
          "dateDecision": "2016-03-16T14:11:56.519864+02:00", 
          "documents": [
            {
              "author": "reviewers", 
              "title": "ComplaintResolution.pdf", 
              "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/9098e60f7f804155b50899f6feea3b92/awards/3ac4201038a7447e8ed75b11dc6b311e/complaints/68436ac844da473090c9880a9f86746f/documents/500c275688454a6582115006ecca9d10?download=40e7b9376abd443a8783af88a2ab73cb", 
              "format": "application/pdf", 
              "documentOf": "tender", 
              "datePublished": "2016-03-16T14:11:56.123720+02:00", 
              "id": "500c275688454a6582115006ecca9d10", 
              "dateModified": "2016-03-16T14:11:56.123757+02:00"
            }
          ], 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "claim", 
          "title": "complaint title", 
          "satisfied": false, 
          "dateEscalated": "2016-03-16T14:11:54.651874+02:00", 
          "dateAnswered": "2016-03-16T14:11:54.282341+02:00", 
          "dateSubmitted": "2016-03-16T14:11:53.917090+02:00", 
          "complaintID": "UA-2016-03-16-000001.7", 
          "date": "2016-03-16T14:11:53.915708+02:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "68436ac844da473090c9880a9f86746f"
        }, 
        {
          "status": "declined", 
          "dateDecision": "2016-03-16T14:11:56.897495+02:00", 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "claim", 
          "title": "complaint title", 
          "satisfied": false, 
          "dateEscalated": "2016-03-16T14:11:55.753218+02:00", 
          "dateAnswered": "2016-03-16T14:11:55.366285+02:00", 
          "dateSubmitted": "2016-03-16T14:11:55.006005+02:00", 
          "complaintID": "UA-2016-03-16-000001.8", 
          "date": "2016-03-16T14:11:55.004630+02:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "3bbafa3666cf4c36ac8d55985f9bdbb4"
        }
      ], 
      "id": "3ac4201038a7447e8ed75b11dc6b311e"
    }, 
    {
      "status": "cancelled", 
      "complaintPeriod": {
        "startDate": "2016-03-16T14:11:48.667483+02:00", 
        "endDate": "2016-03-16T14:11:49.425110+02:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "4193ebb78ed74a5d9c1b34594e78e066", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-03-16T14:11:48.667765+02:00", 
      "id": "41df4556f6b04682bff3a90da10452ba"
    }, 
    {
      "status": "unsuccessful", 
      "documents": [
        {
          "title": "Cancellation_Reason.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/9098e60f7f804155b50899f6feea3b92/awards/e5badabcf6104e809448588e22bb3c60/documents/583eedda2d8a45afb4cb1080e992c28f?download=a0468a8d6b0e4b3bb6dac6036ba955ed", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-03-16T14:11:49.834635+02:00", 
          "id": "583eedda2d8a45afb4cb1080e992c28f", 
          "dateModified": "2016-03-16T14:11:49.834672+02:00"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2016-03-16T14:11:49.425808+02:00", 
        "endDate": "2016-03-17T14:11:50.168982+02:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "4193ebb78ed74a5d9c1b34594e78e066", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-03-16T14:11:49.426178+02:00", 
      "id": "e5badabcf6104e809448588e22bb3c60"
    }, 
    {
      "status": "pending", 
      "complaintPeriod": {
        "startDate": "2016-03-16T14:11:50.169651+02:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "15fe586803774af29341247837d96b20", 
      "value": {
        "currency": "UAH", 
        "amount": 475.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-03-16T14:11:50.169949+02:00", 
      "id": "e2ade2d484f74be38b057c63d18cbbb4"
    }
  ]
}

