PATCH /api/2.0/tenders/cd06ba2ceb4f41be84383c619e335327/awards/51cfe6fc154f4fafb7c067915cf20731?acc_token=719bde683ac54e98b8dad8f703adc3eb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "unsuccessful"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.0/tenders/cd06ba2ceb4f41be84383c619e335327/awards/d3014c2d02d745ffb5388ad27248aa1a

{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "title": "Unsuccessful_Reason.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/cd06ba2ceb4f41be84383c619e335327/awards/51cfe6fc154f4fafb7c067915cf20731/documents/bdd1ca52d01344e29d7160c07b500fa1?download=c0e79cc23aa14d17942362b63d38784d", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-18T18:43:27.562158+02:00", 
        "id": "bdd1ca52d01344e29d7160c07b500fa1", 
        "dateModified": "2016-03-18T18:43:27.562198+02:00"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2016-03-18T18:43:27.291168+02:00", 
      "endDate": "2016-03-19T18:43:27.771437+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "236d2cf299474ee3b67985b4f0420059", 
    "value": {
      "currency": "UAH", 
      "amount": 450.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-03-18T18:43:27.291498+02:00", 
    "id": "51cfe6fc154f4fafb7c067915cf20731"
  }
}

