POST /api/2.3/tenders/8c7840a135e342abb80894985f570f06/awards/be4cb0e0affc4d71a4f1bf64d5311bc9/documents?acc_token=cb1f23460fc94939a34007cdd52598cf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 343
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/1a97d710c5e94114a330f2299550008a?KeyID=9d50f426&Signature=%2BDq67m6Wwx0xoaHw%2FhzoaRvfwDmlISQ7NrOwfho4dwF30ur0lXbbF%2BDv2HJc137kR%2FumeH1B7wQKMdnVa1vSAw%3D%3D", 
    "title": "Cancellation_Reason.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/8c7840a135e342abb80894985f570f06/awards/be4cb0e0affc4d71a4f1bf64d5311bc9/documents/cf8ac5c906e3498384be5618bd9fcb1a

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "Cancellation_Reason.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/1a97d710c5e94114a330f2299550008a?KeyID=9d50f426&Signature=F2oc4WvTTEoAs6JEb1P6ySujTIFxw%2F7mL5kZJo5j6Rm%252Bo%252BO2NGybNROTz6v%2FQSIBJ4CIvFDZrWS2VbD%2FR8DDCTEAAABhAAAAOQAAADcAAABkAAAANwAAADEAAAAwAAAA", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-07-21T17:14:41.313976+03:00", 
    "id": "cf8ac5c906e3498384be5618bd9fcb1a", 
    "dateModified": "2016-07-21T17:14:41.314008+03:00"
  }
}

