PATCH /api/2.3/tenders/1c34544d0e6144f18886b6e59fb8256d/awards/90d2bdbf1b5449f18173020c9c617977?acc_token=cc248e7ef9674336aa17d4528e5e5c77 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: public.api.openprocurement.org

{
  "data": {
    "status": "unsuccessful"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: https://public.api.openprocurement.org/api/2.3/tenders/1c34544d0e6144f18886b6e59fb8256d/awards/84c259abf1ff4ff38e01ff199381e03f

{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "title": "Cancellation_Reason.pdf", 
        "url": "https://public.api.openprocurement.org/api/2.3/tenders/1c34544d0e6144f18886b6e59fb8256d/awards/90d2bdbf1b5449f18173020c9c617977/documents/8ea5e81901324c29b92d5c4fc0c8a19d?download=d1a65bfc0973488987359abe9def5694", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-06-10T15:29:40.422925+03:00", 
        "id": "8ea5e81901324c29b92d5c4fc0c8a19d", 
        "dateModified": "2016-06-10T15:29:40.422964+03:00"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2016-06-10T15:29:40.011539+03:00", 
      "endDate": "2016-06-14T15:29:40.686274+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "42407b31ea5848baaaca5054f3e477cb", 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-06-10T15:29:40.686238+03:00", 
    "id": "90d2bdbf1b5449f18173020c9c617977"
  }
}

