PATCH /api/2.3/tenders/6a4c5d69d2524ac797a4f0e59661ee01/awards/7abd06f2ece54ddda73821816b4faf50?acc_token=f630a981c8c74a98b9c0810e2940d983 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "complaintPeriod": {
      "startDate": "2016-05-12T18:08:08.462170+03:00", 
      "endDate": "2016-05-16T18:08:08.879916+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "b78886a90ac841aa9321cf29f0aac939", 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-05-12T18:08:08.879881+03:00", 
    "id": "7abd06f2ece54ddda73821816b4faf50"
  }
}

