GET /api/0.12/tenders/50596b750c9845d0b87d07a8b6ee0b47/awards?acc_token=b311ea47350341f285504e5c4e0713b2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "unsuccessful", 
      "documents": [
        {
          "title": "Unsuccessful_Reason.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/50596b750c9845d0b87d07a8b6ee0b47/awards/b311ea47350341f285504e5c4e0713b2/documents/8af1a84fbf5e4675910536ef317e2453?download=33c2c6e5857d4ada9b9af942da4983f9", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-03-16T15:13:09.665716+02:00", 
          "id": "8af1a84fbf5e4675910536ef317e2453", 
          "dateModified": "2016-03-16T15:13:09.665761+02:00"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2016-03-16T15:13:09.225603+02:00", 
        "endDate": "2016-03-17T15:13:09.990256+02:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "145ce50404044e5fab37a2ff37bc1253", 
      "value": {
        "currency": "UAH", 
        "amount": 450.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-03-16T15:13:09.226063+02:00", 
      "complaints": [
        {
          "status": "resolved", 
          "documents": [
            {
              "author": "complaint_owner", 
              "title": "Complaint_Attachement.pdf", 
              "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/50596b750c9845d0b87d07a8b6ee0b47/awards/b311ea47350341f285504e5c4e0713b2/complaints/c61ea1ea7d7e4d55b7cc612c38ceefd3/documents/8849013985c04fcbb249f6fc776bfe81?download=7fb904be971b41ac9a7700ffcc9ad1cd", 
              "format": "application/pdf", 
              "documentOf": "tender", 
              "datePublished": "2016-03-16T15:13:12.477409+02:00", 
              "id": "8849013985c04fcbb249f6fc776bfe81", 
              "dateModified": "2016-03-16T15:13:12.477460+02:00"
            }
          ], 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "claim", 
          "title": "complaint title", 
          "satisfied": true, 
          "tendererAction": "Виправлено неконкурентні умови", 
          "dateAnswered": "2016-03-16T15:13:13.989815+02:00", 
          "tendererActionDate": "2016-03-16T15:13:13.989857+02:00", 
          "dateSubmitted": "2016-03-16T15:13:12.856981+02:00", 
          "complaintID": "UA-2016-03-16-000001.5", 
          "date": "2016-03-16T15:13:12.137832+02:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "c61ea1ea7d7e4d55b7cc612c38ceefd3"
        }, 
        {
          "status": "invalid", 
          "dateDecision": "2016-03-16T15:13:15.582663+02:00", 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "claim", 
          "title": "complaint title", 
          "satisfied": false, 
          "dateEscalated": "2016-03-16T15:13:15.177974+02:00", 
          "dateAnswered": "2016-03-16T15:13:14.812543+02:00", 
          "dateSubmitted": "2016-03-16T15:13:13.266028+02:00", 
          "complaintID": "UA-2016-03-16-000001.6", 
          "date": "2016-03-16T15:13:13.260125+02:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "6fb795ede6714437876a5156c6cbfccc"
        }, 
        {
          "status": "resolved", 
          "dateDecision": "2016-03-16T15:13:19.183623+02:00", 
          "documents": [
            {
              "author": "reviewers", 
              "title": "ComplaintResolution.pdf", 
              "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/50596b750c9845d0b87d07a8b6ee0b47/awards/b311ea47350341f285504e5c4e0713b2/complaints/310c67e5c0964efdb2de1cc89771ed70/documents/61fde80f29384442ada9e3f0c575ad4e?download=ec4fa5455acd450daadb96f9bd0a1175", 
              "format": "application/pdf", 
              "documentOf": "tender", 
              "datePublished": "2016-03-16T15:13:18.746140+02:00", 
              "id": "61fde80f29384442ada9e3f0c575ad4e", 
              "dateModified": "2016-03-16T15:13:18.746186+02:00"
            }
          ], 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "claim", 
          "title": "complaint title", 
          "satisfied": false, 
          "dateEscalated": "2016-03-16T15:13:16.918990+02:00", 
          "dateAnswered": "2016-03-16T15:13:16.443490+02:00", 
          "dateSubmitted": "2016-03-16T15:13:15.966087+02:00", 
          "complaintID": "UA-2016-03-16-000001.7", 
          "date": "2016-03-16T15:13:15.963859+02:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "310c67e5c0964efdb2de1cc89771ed70"
        }, 
        {
          "status": "declined", 
          "dateDecision": "2016-03-16T15:13:19.616197+02:00", 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "claim", 
          "title": "complaint title", 
          "satisfied": false, 
          "dateEscalated": "2016-03-16T15:13:18.263910+02:00", 
          "dateAnswered": "2016-03-16T15:13:17.803048+02:00", 
          "dateSubmitted": "2016-03-16T15:13:17.364615+02:00", 
          "complaintID": "UA-2016-03-16-000001.8", 
          "date": "2016-03-16T15:13:17.362439+02:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "cdba5190cbc0452eb0f49e4f5fdc23ab"
        }
      ], 
      "id": "b311ea47350341f285504e5c4e0713b2"
    }, 
    {
      "status": "cancelled", 
      "complaintPeriod": {
        "startDate": "2016-03-16T15:13:09.991080+02:00", 
        "endDate": "2016-03-16T15:13:10.864053+02:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "bbdb4336ff48400eac4bdcc6bfe8dd95", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-03-16T15:13:09.991478+02:00", 
      "id": "2b56561dc406436dbcdd03688de60767"
    }, 
    {
      "status": "unsuccessful", 
      "documents": [
        {
          "title": "Cancellation_Reason.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/50596b750c9845d0b87d07a8b6ee0b47/awards/9b294451bbdc4a4fbe124764f4962d87/documents/c885b1e7a00044edadd425b80bce8474?download=6ddbfc6a928348cd9db00ea61de30597", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-03-16T15:13:11.351351+02:00", 
          "id": "c885b1e7a00044edadd425b80bce8474", 
          "dateModified": "2016-03-16T15:13:11.351403+02:00"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2016-03-16T15:13:10.865199+02:00", 
        "endDate": "2016-03-17T15:13:11.730561+02:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "bbdb4336ff48400eac4bdcc6bfe8dd95", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-03-16T15:13:10.865763+02:00", 
      "id": "9b294451bbdc4a4fbe124764f4962d87"
    }, 
    {
      "status": "pending", 
      "complaintPeriod": {
        "startDate": "2016-03-16T15:13:11.733807+02:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "6d91ae2978844b09a04c2f313a21099d", 
      "value": {
        "currency": "UAH", 
        "amount": 475.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2016-03-16T15:13:11.734380+02:00", 
      "id": "bb8972a91f154dbab0888f6120830d8e"
    }
  ]
}

