POST /api/2.3/tenders/fdc75be18cf448aa828b4e28cd617a1b/awards/ff80bf55091444faa73c25f354808df8/documents?acc_token=4da0724e470d4e789536733278fd4bcd HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 331
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/a0acf1be8fca43e398f6e04ae6301a89?KeyID=9f98b41e&Signature=Kj0Upcl3hH6Fmb8gyWG3syCvNqp1Zguo1HYIgkr5uVXZx3zK1MoFQfahqdZtQEbc6OAD0ggxqF6KdGt5iwxCBw%3D%3D", 
    "title": "Unsuccessful_Reason.pdf", 
    "hash": "00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/fdc75be18cf448aa828b4e28cd617a1b/awards/ff80bf55091444faa73c25f354808df8/documents/a0eb9c9456de4cb8a695a8c83af4f67a

{
  "data": {
    "hash": "00000000000000000000000000000000", 
    "title": "Unsuccessful_Reason.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/a0acf1be8fca43e398f6e04ae6301a89?KeyID=9f98b41e&Signature=Ac3Rl098BHAqIBRWXdZFagkcMzXiXWSlklLIwhHCKWY73v263yUSf8DczWEIqyP%252B0T98gwu670KNahTi1XWaDWEAAAAwAAAAYQAAAGMAAABmAAAAMQAAAGIAAABlAAAA", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-07-20T17:17:23.100581+03:00", 
    "id": "a0eb9c9456de4cb8a695a8c83af4f67a", 
    "dateModified": "2016-07-20T17:17:23.100614+03:00"
  }
}

