PATCH /api/2.0/tenders/4630a487b9cd4ee0abadd23ef4b8e05f/awards/6ba25103f3614f78a635b8fc4cb30295?acc_token=2408bafb138842659f22d6d511a91633 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "cancelled"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.0/tenders/4630a487b9cd4ee0abadd23ef4b8e05f/awards/7a5b06ba5c8f4e3bbb40cf349c7313d5

{
  "data": {
    "status": "cancelled", 
    "documents": [
      {
        "title": "Unsuccessful_Reason.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/4630a487b9cd4ee0abadd23ef4b8e05f/awards/6ba25103f3614f78a635b8fc4cb30295/documents/7cedd31fe0a04893abb933a12c5bed8b?download=ddbc057160e145b6b7379b951c9545df", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-04-15T12:15:22.113966+03:00", 
        "id": "7cedd31fe0a04893abb933a12c5bed8b", 
        "dateModified": "2016-04-15T12:15:22.114011+03:00"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2016-04-15T12:15:21.697359+03:00", 
      "endDate": "2016-04-15T12:15:38.196259+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "bid_id": "189224dd3bf544b7a208500122ce50de", 
    "value": {
      "currency": "UAH", 
      "amount": 450.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-04-15T12:15:21.697823+03:00", 
    "complaints": [
      {
        "status": "resolved", 
        "documents": [
          {
            "author": "complaint_owner", 
            "title": "Complaint_Attachement.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/4630a487b9cd4ee0abadd23ef4b8e05f/awards/6ba25103f3614f78a635b8fc4cb30295/complaints/9f001f1ed640417384afb037e7f43ea1/documents/c8b471ccb52a4193911df981ed1972b9?download=3223e2aa024c4cc5a879f978c65b0a32", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2016-04-15T12:15:25.863950+03:00", 
            "id": "c8b471ccb52a4193911df981ed1972b9", 
            "dateModified": "2016-04-15T12:15:25.863996+03:00"
          }
        ], 
        "description": "complaint description", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "resolved", 
        "type": "claim", 
        "title": "complaint title", 
        "satisfied": true, 
        "tendererAction": "Виправлено неконкурентні умови", 
        "dateAnswered": "2016-04-15T12:15:27.952003+03:00", 
        "tendererActionDate": "2016-04-15T12:15:27.952044+03:00", 
        "dateSubmitted": "2016-04-15T12:15:26.391232+03:00", 
        "complaintID": "UA-2016-04-15-000004.5", 
        "date": "2016-04-15T12:15:25.319519+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "9f001f1ed640417384afb037e7f43ea1"
      }, 
      {
        "status": "invalid", 
        "dateDecision": "2016-04-15T12:15:30.771754+03:00", 
        "description": "complaint description", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "resolved", 
        "type": "claim", 
        "title": "complaint title", 
        "satisfied": false, 
        "dateEscalated": "2016-04-15T12:15:30.213159+03:00", 
        "dateAnswered": "2016-04-15T12:15:29.454104+03:00", 
        "dateSubmitted": "2016-04-15T12:15:26.924174+03:00", 
        "complaintID": "UA-2016-04-15-000004.6", 
        "date": "2016-04-15T12:15:26.922016+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "bfa4790a795742ac85b5d3b253cd944f"
      }, 
      {
        "status": "resolved", 
        "dateDecision": "2016-04-15T12:15:36.480289+03:00", 
        "documents": [
          {
            "author": "reviewers", 
            "title": "ComplaintResolution.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/4630a487b9cd4ee0abadd23ef4b8e05f/awards/6ba25103f3614f78a635b8fc4cb30295/complaints/35f295c30b9a4651850fe58fe9a228d6/documents/229cae42fa3a452f95b51e42b919b3fa?download=58b18ff4392b4794a01311223ded2f25", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2016-04-15T12:15:35.650759+03:00", 
            "id": "229cae42fa3a452f95b51e42b919b3fa", 
            "dateModified": "2016-04-15T12:15:35.650814+03:00"
          }
        ], 
        "description": "complaint description", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "resolved", 
        "type": "claim", 
        "title": "complaint title", 
        "satisfied": false, 
        "dateEscalated": "2016-04-15T12:15:32.504401+03:00", 
        "dateAnswered": "2016-04-15T12:15:31.969478+03:00", 
        "dateSubmitted": "2016-04-15T12:15:31.318568+03:00", 
        "complaintID": "UA-2016-04-15-000004.7", 
        "date": "2016-04-15T12:15:31.313047+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "35f295c30b9a4651850fe58fe9a228d6"
      }, 
      {
        "status": "declined", 
        "dateDecision": "2016-04-15T12:15:37.225017+03:00", 
        "description": "complaint description", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "resolved", 
        "type": "claim", 
        "title": "complaint title", 
        "satisfied": false, 
        "dateEscalated": "2016-04-15T12:15:34.701279+03:00", 
        "dateAnswered": "2016-04-15T12:15:33.863175+03:00", 
        "dateSubmitted": "2016-04-15T12:15:33.052307+03:00", 
        "complaintID": "UA-2016-04-15-000004.8", 
        "date": "2016-04-15T12:15:33.049229+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "6b146e6ad1e246c1b6278420e743ae6b"
      }
    ], 
    "id": "6ba25103f3614f78a635b8fc4cb30295"
  }
}

