PATCH /api/2.3/tenders/f2e454457c114f40a49c282c4c965bee/awards/ae4b3e44c8c6412b93dba9c9c5e4d4d4?acc_token=7f3a278f90804d248ea08f9fcbde845d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "cancelled"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/f2e454457c114f40a49c282c4c965bee/awards/186d625f1fe4416eb7af12be8b690927

{
  "data": {
    "status": "cancelled", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "name.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/d739fba7d40749a5837219f42fdc53a7?KeyID=13edba3f&Signature=GwrDid8y9o2xiNeGnxf0FY0EWvsQxRaGfmhY1zQPz6JZBjm1tAH%2FKH1N9hJgxrTFs1dFgeONUPE2YRr%252Bwgs2Bw%253D%253D", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2017-02-27T15:29:41.366042+02:00", 
        "id": "6a24b1400fc3460483387b3cb349bc8b", 
        "dateModified": "2017-02-27T15:29:41.366081+02:00"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2017-02-27T15:29:40.925631+02:00", 
      "endDate": "2017-02-27T15:29:41.866060+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "877ee8ece04742c3b3738b2053510f86", 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-02-27T15:29:41.880510+02:00", 
    "id": "ae4b3e44c8c6412b93dba9c9c5e4d4d4"
  }
}

