PATCH /api/0.12/tenders/50596b750c9845d0b87d07a8b6ee0b47/awards/9b294451bbdc4a4fbe124764f4962d87?acc_token=a122c83b42a442ec9a3c12992e41755f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "unsuccessful"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/0.12/tenders/50596b750c9845d0b87d07a8b6ee0b47/awards/bb8972a91f154dbab0888f6120830d8e

{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "title": "Cancellation_Reason.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/50596b750c9845d0b87d07a8b6ee0b47/awards/9b294451bbdc4a4fbe124764f4962d87/documents/c885b1e7a00044edadd425b80bce8474?download=6ddbfc6a928348cd9db00ea61de30597", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T15:13:11.351351+02:00", 
        "id": "c885b1e7a00044edadd425b80bce8474", 
        "dateModified": "2016-03-16T15:13:11.351403+02:00"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2016-03-16T15:13:10.865199+02:00", 
      "endDate": "2016-03-17T15:13:11.730561+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "bbdb4336ff48400eac4bdcc6bfe8dd95", 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-03-16T15:13:10.865763+02:00", 
    "id": "9b294451bbdc4a4fbe124764f4962d87"
  }
}

