PATCH /api/2.3/tenders/03461a7a11b24926a1882f544f5b19d7/awards/72a4d40debe940eea7407530731d9398/complaints/ec139df5c9e440c585f3753a980d0adb?acc_token=99e1835f3c0242f888a5342b5ef5f6d0 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "claim"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "claim", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/0de176d055104ab09bb07f8c9d5e9a85?KeyID=c33983f9&Signature=BfmBkBISZqVipkDADvhuCAhfgCcjXli5Kfm%252Bnn0oQubOkU4J2x%2FLi5biA4XoPqgprCMPTPK6L%252BUXUXT6U88gAw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-06-12T14:11:41.650204+03:00", 
        "id": "2ae37400e7804f87b78df7faaa71f4f1", 
        "dateModified": "2017-06-12T14:11:41.650234+03:00"
      }
    ], 
    "description": "complaint description", 
    "title": "complaint title", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateSubmitted": "2017-06-12T14:11:41.870068+03:00", 
    "complaintID": "UA-2017-06-12-000001.5", 
    "date": "2017-06-12T14:11:41.880951+03:00", 
    "type": "claim", 
    "id": "ec139df5c9e440c585f3753a980d0adb"
  }
}

