PATCH /api/2.3/tenders/6a4c5d69d2524ac797a4f0e59661ee01/awards/ad5615dcee1d4d1296039b9da0eba5a6/complaints/e4e9b22e70844b0f9ef558f7e3931186?acc_token=e2e45bcaa7e9458995af4cd56c50c074 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "pending", 
    "satisfied": false
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "pending", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "satisfied": false, 
    "dateEscalated": "2016-05-12T18:08:13.274730+03:00", 
    "dateAnswered": "2016-05-12T18:08:12.922191+03:00", 
    "dateSubmitted": "2016-05-12T18:08:11.573022+03:00", 
    "complaintID": "UA-2016-05-12-000001.6", 
    "date": "2016-05-12T18:08:11.571021+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "e4e9b22e70844b0f9ef558f7e3931186"
  }
}

