PATCH /api/2.0/tenders/4630a487b9cd4ee0abadd23ef4b8e05f/awards/6ba25103f3614f78a635b8fc4cb30295/complaints/bfa4790a795742ac85b5d3b253cd944f?acc_token=097267c36ca54cf99dac911ea9659efa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "pending", 
    "satisfied": false
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "pending", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "satisfied": false, 
    "dateEscalated": "2016-04-15T12:15:30.213159+03:00", 
    "dateAnswered": "2016-04-15T12:15:29.454104+03:00", 
    "dateSubmitted": "2016-04-15T12:15:26.924174+03:00", 
    "complaintID": "UA-2016-04-15-000004.6", 
    "date": "2016-04-15T12:15:26.922016+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "bfa4790a795742ac85b5d3b253cd944f"
  }
}

