PATCH /api/0.12/tenders/02318d921ca04fd2877ae9b6c02e9425/awards/2bfec8100a2d41309a967f7fa612af96/complaints/fea285b32d624008a2f34521034dc2b0 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "declined"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "declined", 
    "dateDecision": "2016-02-24T11:29:25.677398+02:00", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "satisfied": false, 
    "dateEscalated": "2016-02-24T11:29:25.004944+02:00", 
    "dateAnswered": "2016-02-24T11:29:24.795253+02:00", 
    "dateSubmitted": "2016-02-24T11:29:24.582716+02:00", 
    "date": "2016-02-24T11:29:24.580933+02:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "fea285b32d624008a2f34521034dc2b0"
  }
}

