PATCH /api/2.0/tenders/4630a487b9cd4ee0abadd23ef4b8e05f/awards/6ba25103f3614f78a635b8fc4cb30295/complaints/6b146e6ad1e246c1b6278420e743ae6b HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "declined"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "declined", 
    "dateDecision": "2016-04-15T12:15:37.225017+03:00", 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "claim", 
    "title": "complaint title", 
    "satisfied": false, 
    "dateEscalated": "2016-04-15T12:15:34.701279+03:00", 
    "dateAnswered": "2016-04-15T12:15:33.863175+03:00", 
    "dateSubmitted": "2016-04-15T12:15:33.052307+03:00", 
    "complaintID": "UA-2016-04-15-000004.8", 
    "date": "2016-04-15T12:15:33.049229+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "6b146e6ad1e246c1b6278420e743ae6b"
  }
}

