GET /api/2.0/tenders/d14225f722384c46a31b4e4470b66d8d/awards/4e4776f63dd0487c9841a54dff82bb6c/complaints/823c3718be1547c8aa70129d81910994 HTTP/1.0
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "claim", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/d14225f722384c46a31b4e4470b66d8d/awards/4e4776f63dd0487c9841a54dff82bb6c/complaints/823c3718be1547c8aa70129d81910994/documents/667e6da7d4a545cd914dc857105d0297?download=5c4475e3ec9e4efb964a56cfd99093ae", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T17:54:19.575638+02:00", 
        "id": "667e6da7d4a545cd914dc857105d0297", 
        "dateModified": "2016-03-16T17:54:19.575679+02:00"
      }
    ], 
    "description": "complaint description", 
    "title": "complaint title", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "dateSubmitted": "2016-03-16T17:54:19.903649+02:00", 
    "complaintID": "UA-2016-03-16-000001.5", 
    "date": "2016-03-16T17:54:19.269279+02:00", 
    "type": "claim", 
    "id": "823c3718be1547c8aa70129d81910994"
  }
}

