PATCH /api/2.3/tenders/eeb9177097a14a8c80ca0d1c8b202a00/awards/86d3f73dd7094865a9fd4966584c62ae/complaints/b5c19009d623453b93ac13f2f0fe0b78 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "dateDecision": "2016-07-21T17:18:02.667772+03:00", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "reviewers", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/fddb600727e24cbca910668c130af96f?KeyID=a1a42480&Signature=wB7r3gbiyuijB6Cv6lHHcFF4asw9kUgDSRV3Pz6cR1PUorYCaBYY8lkZADWEmqXBELB5LTlFFGawvMt6P2SBAGYAAABkAAAAZAAAAGIAAAA2AAAAMAAAADAAAAA3AAAA", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-07-21T17:18:02.305563+03:00", 
        "id": "9bb5ad67bfad43a9a58bc972b1b31613", 
        "dateModified": "2016-07-21T17:18:02.305597+03:00"
      }
    ], 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "title": "complaint title", 
    "satisfied": false, 
    "dateEscalated": "2016-07-21T17:18:00.867577+03:00", 
    "dateAnswered": "2016-07-21T17:18:00.516074+03:00", 
    "dateSubmitted": "2016-07-21T17:18:00.195924+03:00", 
    "complaintID": "UA-2016-07-21-000001.7", 
    "date": "2016-07-21T17:18:02.685259+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "b5c19009d623453b93ac13f2f0fe0b78"
  }
}

