PATCH /api/2.0/tenders/cd06ba2ceb4f41be84383c619e335327/awards/51cfe6fc154f4fafb7c067915cf20731/complaints/07e45d7b51494845bafaa16307ca92be?acc_token=719bde683ac54e98b8dad8f703adc3eb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 442
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "answered", 
    "resolutionType": "resolved", 
    "tendererAction": "Виправлено неконкурентні умови", 
    "resolution": "Виправлено неконкурентні умови"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "answered", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/cd06ba2ceb4f41be84383c619e335327/awards/51cfe6fc154f4fafb7c067915cf20731/complaints/07e45d7b51494845bafaa16307ca92be/documents/0e23f8c1504541cdaaea0c64ddd8d137?download=3a533903e1ee465aac6316ccf918148e", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-18T18:43:29.589180+02:00", 
        "id": "0e23f8c1504541cdaaea0c64ddd8d137", 
        "dateModified": "2016-03-18T18:43:29.589220+02:00"
      }
    ], 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "claim", 
    "title": "complaint title", 
    "tendererAction": "Виправлено неконкурентні умови", 
    "dateAnswered": "2016-03-18T18:43:30.623807+02:00", 
    "tendererActionDate": "2016-03-18T18:43:30.623847+02:00", 
    "dateSubmitted": "2016-03-18T18:43:29.866178+02:00", 
    "complaintID": "UA-2016-03-18-000001.5", 
    "date": "2016-03-18T18:43:29.333444+02:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "07e45d7b51494845bafaa16307ca92be"
  }
}

