PATCH /api/2.0/tenders/9098e60f7f804155b50899f6feea3b92/awards/3ac4201038a7447e8ed75b11dc6b311e/complaints/1c20f274081043809860d1ce070bdb0a?acc_token=58163224390848489c45b49b0022c993 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "satisfied": true
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/9098e60f7f804155b50899f6feea3b92/awards/3ac4201038a7447e8ed75b11dc6b311e/complaints/1c20f274081043809860d1ce070bdb0a/documents/da7eda23a733493eaee8ca8eeda897ef?download=e535f081c24d4df291decf3c69cd3530", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T14:11:50.799265+02:00", 
        "id": "da7eda23a733493eaee8ca8eeda897ef", 
        "dateModified": "2016-03-16T14:11:50.799303+02:00"
      }
    ], 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "claim", 
    "title": "complaint title", 
    "satisfied": true, 
    "tendererAction": "Виправлено неконкурентні умови", 
    "dateAnswered": "2016-03-16T14:11:52.007274+02:00", 
    "tendererActionDate": "2016-03-16T14:11:52.007297+02:00", 
    "dateSubmitted": "2016-03-16T14:11:51.134452+02:00", 
    "complaintID": "UA-2016-03-16-000001.5", 
    "date": "2016-03-16T14:11:50.470674+02:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "1c20f274081043809860d1ce070bdb0a"
  }
}

