POST /api/2.0/tenders/5daa560c72734310ac6a73489233b32b/awards/ec1c1fab15a34b328516660d3d52e257/complaints?acc_token=d1dbcbd7cceb493cb03c31e4ceb1f75c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 880
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "title": "complaint title", 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.0/tenders/5daa560c72734310ac6a73489233b32b/awards/ec1c1fab15a34b328516660d3d52e257/complaints/61b5ee1216d64393af578f82b36077b9

{
  "access": {
    "token": "b8ea919ebfbd416ba5c88d0df6c8747a"
  }, 
  "data": {
    "status": "draft", 
    "description": "complaint description", 
    "title": "complaint title", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "complaintID": "UA-2016-03-14-000001.5", 
    "date": "2016-03-14T13:38:25.629619+02:00", 
    "type": "claim", 
    "id": "61b5ee1216d64393af578f82b36077b9"
  }
}

