PATCH /api/2.0/tenders/df482adf4b1a41d38ff9d7f1fd8888c3/awards/c53e53a0e11c486ba2e3675edfb19d28/complaints/26a86a7e7887444db3c4cc1a9ce384b7?acc_token=467a486061944a1db3647644a4353b9b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 442
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "answered", 
    "resolutionType": "resolved", 
    "tendererAction": "Виправлено неконкурентні умови", 
    "resolution": "Виправлено неконкурентні умови"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "answered", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/df482adf4b1a41d38ff9d7f1fd8888c3/awards/c53e53a0e11c486ba2e3675edfb19d28/complaints/26a86a7e7887444db3c4cc1a9ce384b7/documents/480c607f36ba4a8495663b34af597f6b?download=2d396ecceb1640308f5c66364c9350f8", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T11:22:20.207949+02:00", 
        "id": "480c607f36ba4a8495663b34af597f6b", 
        "dateModified": "2016-03-16T11:22:20.207988+02:00"
      }
    ], 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "claim", 
    "title": "complaint title", 
    "tendererAction": "Виправлено неконкурентні умови", 
    "dateAnswered": "2016-03-16T11:22:21.480153+02:00", 
    "tendererActionDate": "2016-03-16T11:22:21.480175+02:00", 
    "dateSubmitted": "2016-03-16T11:22:20.553772+02:00", 
    "complaintID": "UA-2016-03-16-000001.5", 
    "date": "2016-03-16T11:22:19.883796+02:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "26a86a7e7887444db3c4cc1a9ce384b7"
  }
}

