GET /api/0.12/tenders/6e4678dd3a8749d1b16741168a8e3506/awards/299f0ae09a83412ca76546531459ffc2/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "claim", 
      "documents": [
        {
          "author": "complaint_owner", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/6e4678dd3a8749d1b16741168a8e3506/awards/299f0ae09a83412ca76546531459ffc2/complaints/46d51263d20d49089997fd7e57cc6bda/documents/9c3ebad92f654b1e818d32b4e146b197?download=90d0d928591545e6886e24d83154404c", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-03-18T15:00:26.092335+02:00", 
          "id": "9c3ebad92f654b1e818d32b4e146b197", 
          "dateModified": "2016-03-18T15:00:26.092375+02:00"
        }
      ], 
      "description": "complaint description", 
      "title": "complaint title", 
      "author": {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }, 
      "dateSubmitted": "2016-03-18T15:00:26.387767+02:00", 
      "complaintID": "UA-2016-03-18-000001.5", 
      "date": "2016-03-18T15:00:25.826959+02:00", 
      "type": "claim", 
      "id": "46d51263d20d49089997fd7e57cc6bda"
    }, 
    {
      "status": "claim", 
      "description": "complaint description", 
      "title": "complaint title", 
      "author": {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }, 
      "dateSubmitted": "2016-03-18T15:00:26.684744+02:00", 
      "complaintID": "UA-2016-03-18-000001.6", 
      "date": "2016-03-18T15:00:26.682793+02:00", 
      "type": "claim", 
      "id": "e50b6fb6e7844dfdaca6529a20235007"
    }
  ]
}

