PATCH /api/0.12/tenders/34da1cd9ac4343e79f4b163d0a583125/awards/0da7879e7234468c9ae9c5766edd805c/complaints/cd0bc6c7a74f486eb0076a4412c3e997?acc_token=229fc1f30681400f9e6de3bcd32dd2f4 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "satisfied": true
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/34da1cd9ac4343e79f4b163d0a583125/awards/0da7879e7234468c9ae9c5766edd805c/complaints/cd0bc6c7a74f486eb0076a4412c3e997/documents/2394bd27c14148869eb200b5246aed03?download=2c0709213c414971a83abee31a4f0502", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-02-26T15:08:49.134667+02:00", 
        "id": "2394bd27c14148869eb200b5246aed03", 
        "dateModified": "2016-02-26T15:08:49.134704+02:00"
      }
    ], 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "claim", 
    "title": "complaint title", 
    "satisfied": true, 
    "tendererAction": "Виправлено неконкурентні умови", 
    "dateAnswered": "2016-02-26T15:08:49.979786+02:00", 
    "tendererActionDate": "2016-02-26T15:08:49.979819+02:00", 
    "dateSubmitted": "2016-02-26T15:08:49.343202+02:00", 
    "date": "2016-02-26T15:08:48.935630+02:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "cd0bc6c7a74f486eb0076a4412c3e997"
  }
}

