PATCH /api/0.12/tenders/6497d563e3fd40a187641dcebd1e27ca/awards/e2966342db884728a80e870b85186d8e/complaints/d301e996ba364e2d92b89e9de6bb0795?acc_token=49271b33dd034232a8925d36154451c5 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "claim"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "claim", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/6497d563e3fd40a187641dcebd1e27ca/awards/e2966342db884728a80e870b85186d8e/complaints/d301e996ba364e2d92b89e9de6bb0795/documents/6b08a768216a48018f17741f67b2df65?download=5818c523f5674e9396c3cdad070c9f29", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-14T21:28:59.845093+02:00", 
        "id": "6b08a768216a48018f17741f67b2df65", 
        "dateModified": "2016-03-14T21:28:59.845153+02:00"
      }
    ], 
    "description": "complaint description", 
    "title": "complaint title", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "dateSubmitted": "2016-03-14T21:29:00.158780+02:00", 
    "complaintID": "UA-2016-03-14-000001.5", 
    "date": "2016-03-14T21:28:59.540517+02:00", 
    "type": "claim", 
    "id": "d301e996ba364e2d92b89e9de6bb0795"
  }
}

