GET /api/2.0/tenders/4630a487b9cd4ee0abadd23ef4b8e05f/awards/6ba25103f3614f78a635b8fc4cb30295/complaints/9f001f1ed640417384afb037e7f43ea1 HTTP/1.0
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "claim", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/4630a487b9cd4ee0abadd23ef4b8e05f/awards/6ba25103f3614f78a635b8fc4cb30295/complaints/9f001f1ed640417384afb037e7f43ea1/documents/c8b471ccb52a4193911df981ed1972b9?download=3223e2aa024c4cc5a879f978c65b0a32", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-04-15T12:15:25.863950+03:00", 
        "id": "c8b471ccb52a4193911df981ed1972b9", 
        "dateModified": "2016-04-15T12:15:25.863996+03:00"
      }
    ], 
    "description": "complaint description", 
    "title": "complaint title", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateSubmitted": "2016-04-15T12:15:26.391232+03:00", 
    "complaintID": "UA-2016-04-15-000004.5", 
    "date": "2016-04-15T12:15:25.319519+03:00", 
    "type": "claim", 
    "id": "9f001f1ed640417384afb037e7f43ea1"
  }
}

