PATCH /api/2.3/tenders/6e33b56945624315afece8e75af7193c/awards/aec061c3b3234a9981a292ae161d2ece/complaints/fc1eef6ef50d4656b981aae8bb181467?acc_token=3df7c9a8797747c0b56aa8ac54c8ac87 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "satisfied": true
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/8f6064cff50e40e98b6a0d3a5bf285f3?KeyID=1a1ebb61&Signature=GUupJVcUEjCGb8j6wOYSyvTs7P6XMvDfE%2FK1BBt82UFMqRa8qpjkQ2qziQjf8yqB5eZ5KRggHUyaUA0qhE67AQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-07-25T17:36:53.000914+03:00", 
        "id": "96ad4bc79c704f6eb094b83bf2ca817a", 
        "dateModified": "2017-07-25T17:36:53.000946+03:00"
      }
    ], 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "claim", 
    "title": "complaint title", 
    "satisfied": true, 
    "tendererAction": "Виправлено неконкурентні умови", 
    "dateAnswered": "2017-07-25T17:36:53.465653+03:00", 
    "tendererActionDate": "2017-07-25T17:36:53.465668+03:00", 
    "dateSubmitted": "2017-07-25T17:36:53.127004+03:00", 
    "complaintID": "UA-2017-07-25-000001.5", 
    "date": "2017-07-25T17:36:53.605801+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "fc1eef6ef50d4656b981aae8bb181467"
  }
}

