PATCH /api/2.3/tenders/fdc75be18cf448aa828b4e28cd617a1b/awards/ff80bf55091444faa73c25f354808df8/complaints/322a384479b64b5bb4e97a9667a3e12d?acc_token=4a90b5a2141849cd95a610c1b81af897 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "pending", 
    "satisfied": false
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "pending", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "satisfied": false, 
    "dateEscalated": "2016-07-20T17:17:27.550415+03:00", 
    "dateAnswered": "2016-07-20T17:17:27.204316+03:00", 
    "dateSubmitted": "2016-07-20T17:17:25.961933+03:00", 
    "complaintID": "UA-2016-07-20-000001.6", 
    "date": "2016-07-20T17:17:25.960444+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "322a384479b64b5bb4e97a9667a3e12d"
  }
}

