POST /api/2.0/tenders/9098e60f7f804155b50899f6feea3b92/awards/3ac4201038a7447e8ed75b11dc6b311e/complaints?acc_token=e37974f048b5424992153051e9bc7756 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 899
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "claim", 
    "title": "complaint title", 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.0/tenders/9098e60f7f804155b50899f6feea3b92/awards/3ac4201038a7447e8ed75b11dc6b311e/complaints/f8c244e946c44fa59fa09dafecc20e49

{
  "access": {
    "token": "92fb07a5c9b24b0287da039b59b94e14"
  }, 
  "data": {
    "status": "claim", 
    "description": "complaint description", 
    "title": "complaint title", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "dateSubmitted": "2016-03-16T14:11:51.484291+02:00", 
    "complaintID": "UA-2016-03-16-000001.6", 
    "date": "2016-03-16T14:11:51.482928+02:00", 
    "type": "claim", 
    "id": "f8c244e946c44fa59fa09dafecc20e49"
  }
}

