POST /api/2.3/tenders/b5f0fd0ef8684ba997e3cd344fd1d131/awards/6a21aa7f911f424d85e354e59a7e7c84/complaints/2bc1563d8b8847b89989fa9f46936cdf/documents?acc_token=1701194854bd4ab0bda89d03fababb85 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 347
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/e819bad42f6b4d978e82c905725bc0e8?KeyID=e440c6be&Signature=k6%2Bc97kMbr6tTJfUGFh%2F5BGg6HP0oTLXSoiE%2FTY9JYM%2BS0mbAw9OqKKxLSKjHVKo1xdty%2FKdWsxrNksrJRqvBw%3D%3D",
    "title": "Complaint_Attachement.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/b5f0fd0ef8684ba997e3cd344fd1d131/awards/6a21aa7f911f424d85e354e59a7e7c84/complaints/2bc1563d8b8847b89989fa9f46936cdf/documents/6ca2c2747ae74380ac3c7bfba9110e46

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "title": "Complaint_Attachement.pdf",
    "url": "http://public.docs-sandbox.openprocurement.org/get/e819bad42f6b4d978e82c905725bc0e8?KeyID=e440c6be&Signature=uKNUm6O3dKOqJOvmgswNPVXfu%2FdW8dgGhc8QdUfOdhiQtaLsQNduvB6ErmvXfCKpOtqP7yfg91UuMBg8CYSODA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-06-24T18:05:40.656135+03:00", 
    "id": "6ca2c2747ae74380ac3c7bfba9110e46", 
    "dateModified": "2017-06-24T18:05:40.656169+03:00"
  }
}

