PATCH /api/2.0/tenders/cd06ba2ceb4f41be84383c619e335327/awards/51cfe6fc154f4fafb7c067915cf20731/complaints/a3f62a110ea44e239c3924f20b3473db HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "dateDecision": "2016-03-18T18:43:34.382146+02:00", 
    "documents": [
      {
        "author": "reviewers", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/cd06ba2ceb4f41be84383c619e335327/awards/51cfe6fc154f4fafb7c067915cf20731/complaints/a3f62a110ea44e239c3924f20b3473db/documents/f0a597299bda4bbebedf036c93543505?download=4275ed4d254645e09a48588a532488c8", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-18T18:43:34.056128+02:00", 
        "id": "f0a597299bda4bbebedf036c93543505", 
        "dateModified": "2016-03-18T18:43:34.056174+02:00"
      }
    ], 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "claim", 
    "title": "complaint title", 
    "satisfied": false, 
    "dateEscalated": "2016-03-18T18:43:32.758579+02:00", 
    "dateAnswered": "2016-03-18T18:43:32.447979+02:00", 
    "dateSubmitted": "2016-03-18T18:43:32.152012+02:00", 
    "complaintID": "UA-2016-03-18-000001.7", 
    "date": "2016-03-18T18:43:32.150497+02:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "a3f62a110ea44e239c3924f20b3473db"
  }
}

