PATCH /api/2.3/tenders/3348c29949f84857a9a51573a0ff47c7/awards/c37edfe039294951b6eb3813b6d64ce2/complaints/e6f9e32cafca46e89a70bae2744eddd0 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "dateDecision": "2017-06-19T18:27:52.506239+03:00", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "reviewers", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/199b73e08ed3436a9c4acc8365e8c739?KeyID=9e5fca15&Signature=RTi5nld4qIXGkb1y8DgrPHtaiopyJT44mEqEpkFbF1YcoqdZVNKktaSAT%252BkkRKFRJYu7WoKclj7EOE6KveKxAQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-06-19T18:27:52.192526+03:00", 
        "id": "899f00d964784e55b3e440bd49369089", 
        "dateModified": "2017-06-19T18:27:52.192559+03:00"
      }
    ], 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "title": "complaint title", 
    "satisfied": false, 
    "dateEscalated": "2017-06-19T18:27:50.991601+03:00", 
    "dateAnswered": "2017-06-19T18:27:50.708113+03:00", 
    "dateSubmitted": "2017-06-19T18:27:50.420378+03:00", 
    "complaintID": "UA-2017-06-19-000001.7", 
    "date": "2017-06-19T18:27:52.520854+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "e6f9e32cafca46e89a70bae2744eddd0"
  }
}

