GET /api/2.0/tenders/9098e60f7f804155b50899f6feea3b92/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "claim", 
      "documents": [
        {
          "author": "complaint_owner", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/9098e60f7f804155b50899f6feea3b92/complaints/3da5f29e64964b9b8df8a120ecc31ded/documents/ff18cefce00b4700ad185967b054a54f?download=69935edf78f14eb6843f6b9a860fb9ca", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-03-16T14:11:42.603811+02:00", 
          "id": "ff18cefce00b4700ad185967b054a54f", 
          "dateModified": "2016-03-16T14:11:42.603862+02:00"
        }
      ], 
      "description": "complaint description", 
      "title": "complaint title", 
      "dateSubmitted": "2016-03-16T14:11:42.778729+02:00", 
      "complaintID": "UA-2016-03-16-000001.1", 
      "date": "2016-03-16T14:11:42.272887+02:00", 
      "type": "claim", 
      "id": "3da5f29e64964b9b8df8a120ecc31ded"
    }, 
    {
      "status": "claim", 
      "description": "complaint description", 
      "title": "complaint title", 
      "dateSubmitted": "2016-03-16T14:11:42.958631+02:00", 
      "complaintID": "UA-2016-03-16-000001.2", 
      "date": "2016-03-16T14:11:42.957340+02:00", 
      "type": "claim", 
      "id": "80de0226391d4ada81b1b0546e845d3c"
    }
  ]
}

