PATCH /api/0.12/tenders/081046e7e46a421696e00567725c24cc/complaints/7cce7f7b9a1948708ebbd4912e8add14 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "declined"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "declined", 
    "dateDecision": "2016-02-04T16:00:45.328393+02:00", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "satisfied": false, 
    "dateEscalated": "2016-02-04T16:00:44.816963+02:00", 
    "dateAnswered": "2016-02-04T16:00:44.661267+02:00", 
    "dateSubmitted": "2016-02-04T16:00:44.504813+02:00", 
    "date": "2016-02-04T16:00:44.503301+02:00", 
    "resolution": "Виправлено", 
    "id": "7cce7f7b9a1948708ebbd4912e8add14"
  }
}

