PATCH /api/0.12/tenders/081046e7e46a421696e00567725c24cc/complaints/0b102ca9562b47f6b25cd9655b187d77 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "dateDecision": "2016-02-04T16:00:45.168540+02:00", 
    "documents": [
      {
        "author": "reviewers", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/081046e7e46a421696e00567725c24cc/complaints/0b102ca9562b47f6b25cd9655b187d77/documents/58426ddf13b845ff9cbc8d1eac062004?download=a23b276261394a44bcc850a0c59e1da7", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-02-04T16:00:44.992301+02:00", 
        "id": "58426ddf13b845ff9cbc8d1eac062004", 
        "dateModified": "2016-02-04T16:00:44.992335+02:00"
      }
    ], 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "title": "complaint title", 
    "satisfied": false, 
    "dateEscalated": "2016-02-04T16:00:44.361541+02:00", 
    "dateAnswered": "2016-02-04T16:00:44.211245+02:00", 
    "dateSubmitted": "2016-02-04T16:00:44.057996+02:00", 
    "date": "2016-02-04T16:00:44.056539+02:00", 
    "resolution": "Виправлено", 
    "id": "0b102ca9562b47f6b25cd9655b187d77"
  }
}

