PATCH /api/2.0/tenders/4630a487b9cd4ee0abadd23ef4b8e05f/complaints/915222b1fcae47cc9928325358a36a0a HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "invalid"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "invalid", 
    "dateDecision": "2016-04-15T12:15:15.805455+03:00", 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "title": "complaint title", 
    "satisfied": false, 
    "dateEscalated": "2016-04-15T12:15:15.511073+03:00", 
    "dateAnswered": "2016-04-15T12:15:15.295870+03:00", 
    "dateSubmitted": "2016-04-15T12:15:14.276950+03:00", 
    "complaintID": "UA-2016-04-15-000004.2", 
    "date": "2016-04-15T12:15:14.275077+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "915222b1fcae47cc9928325358a36a0a"
  }
}

