PATCH /api/2.3/tenders/6e33b56945624315afece8e75af7193c/complaints/3382f6727fc94edc947ff016fcedad11?acc_token=463edbad1cd743ad842e367ec778d835 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 52
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "satisfied": false
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "satisfied": false, 
    "dateAnswered": "2017-07-25T17:36:51.045464+03:00", 
    "dateSubmitted": "2017-07-25T17:36:50.854956+03:00", 
    "complaintID": "UA-2017-07-25-000001.2", 
    "date": "2017-07-25T17:36:51.100829+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "3382f6727fc94edc947ff016fcedad11"
  }
}

