POST /api/2.0/tenders/d14225f722384c46a31b4e4470b66d8d/complaints HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 880
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "title": "complaint title", 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.0/tenders/d14225f722384c46a31b4e4470b66d8d/complaints/980b33632b814c878a54c7c77b67726e

{
  "access": {
    "token": "5f320b2a7380435bbbfadfd3a3af3bda"
  }, 
  "data": {
    "status": "draft", 
    "description": "complaint description", 
    "title": "complaint title", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "complaintID": "UA-2016-03-16-000001.1", 
    "date": "2016-03-16T17:54:11.163784+02:00", 
    "type": "claim", 
    "id": "980b33632b814c878a54c7c77b67726e"
  }
}

