PATCH /api/2.0/tenders/5daa560c72734310ac6a73489233b32b/complaints/f4c5ec0871fc44429209d6ca39eef772?acc_token=e48826464bdf4135a9188e28da3dd5ad HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "claim"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "claim", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/5daa560c72734310ac6a73489233b32b/complaints/f4c5ec0871fc44429209d6ca39eef772/documents/ab875db29b6f4e089e944d9a3f266242?download=976de77b2c774c5dab55a9e02a8aea61", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-14T13:38:19.696521+02:00", 
        "id": "ab875db29b6f4e089e944d9a3f266242", 
        "dateModified": "2016-03-14T13:38:19.696560+02:00"
      }
    ], 
    "description": "complaint description", 
    "title": "complaint title", 
    "dateSubmitted": "2016-03-14T13:38:19.813382+02:00", 
    "complaintID": "UA-2016-03-14-000001.1", 
    "date": "2016-03-14T13:38:19.406935+02:00", 
    "type": "claim", 
    "id": "f4c5ec0871fc44429209d6ca39eef772"
  }
}

