PATCH /api/2.0/tenders/9098e60f7f804155b50899f6feea3b92/complaints/3da5f29e64964b9b8df8a120ecc31ded?acc_token=14a17589ebe3463a84cf85c4def3c497 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "satisfied": true
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/9098e60f7f804155b50899f6feea3b92/complaints/3da5f29e64964b9b8df8a120ecc31ded/documents/ff18cefce00b4700ad185967b054a54f?download=69935edf78f14eb6843f6b9a860fb9ca", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T14:11:42.603811+02:00", 
        "id": "ff18cefce00b4700ad185967b054a54f", 
        "dateModified": "2016-03-16T14:11:42.603862+02:00"
      }
    ], 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "satisfied": true, 
    "tendererAction": "Виправлено неконкурентні умови", 
    "dateAnswered": "2016-03-16T14:11:43.224649+02:00", 
    "tendererActionDate": "2016-03-16T14:11:43.224673+02:00", 
    "dateSubmitted": "2016-03-16T14:11:42.778729+02:00", 
    "complaintID": "UA-2016-03-16-000001.1", 
    "date": "2016-03-16T14:11:42.272887+02:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "3da5f29e64964b9b8df8a120ecc31ded"
  }
}

