POST /api/2.3/tenders/3348c29949f84857a9a51573a0ff47c7/complaints/7e29a56cebf3434cadaf3667c6eb101d/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 339
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/d9cda2834977461898b25fcc401bbfc4?KeyID=9e5fca15&Signature=rJJdkDdYzYngA%2BF0M22lb7tiWTlnpy%2B2Idrmt1Gu2oLiJcTrg1FNWcsWXD4xkTie6T8S9jCxxZhYZDvSp6o3DA%3D%3D", 
    "title": "ComplaintResolution.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/3348c29949f84857a9a51573a0ff47c7/complaints/7e29a56cebf3434cadaf3667c6eb101d/documents/064d9505b40049468ed760685cfab281

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "reviewers", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/d9cda2834977461898b25fcc401bbfc4?KeyID=9e5fca15&Signature=Zfqv81v9HNLpwihUj98LTiUbQpgE4bt%2FdEMfvuKGIm65iwvw1EdWcNnWlo2BskLTfl6G5eQ%2FyE5%2FJHxZCCBpCQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-06-19T18:27:44.743329+03:00", 
    "id": "064d9505b40049468ed760685cfab281", 
    "dateModified": "2017-06-19T18:27:44.743361+03:00"
  }
}

