PATCH /api/2.3/tenders/6fb28391664b4e31b9002882b4d67573/complaints/6ec3802538ad4643ac112a89a7e52f55?acc_token=71c2431dfe474d03a20bd49fe076f152 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 442
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "answered", 
    "resolutionType": "resolved", 
    "tendererAction": "Виправлено неконкурентні умови", 
    "resolution": "Виправлено неконкурентні умови"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "answered", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/b78096bc0a4d4ae1b7427b8730098ca1?KeyID=73cdfe25&Signature=3P6CkyA2RtT1ML1EqxrREH7uh%252BI7mdrpt9LfX72LUv4VqKhthAvxLqN7dMXsQdL2107VBUj%252BD5PUx1MYrn5YBg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-06-24T18:00:27.436436+03:00", 
        "id": "6a37113bab1042be8af7d4c5595e3697", 
        "dateModified": "2017-06-24T18:00:27.436470+03:00"
      }
    ], 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "tendererAction": "Виправлено неконкурентні умови", 
    "dateAnswered": "2017-06-24T18:00:27.785797+03:00", 
    "tendererActionDate": "2017-06-24T18:00:27.785825+03:00", 
    "dateSubmitted": "2017-06-24T18:00:27.531195+03:00", 
    "complaintID": "UA-2017-06-24-000001.1", 
    "date": "2017-06-24T18:00:27.791221+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "6ec3802538ad4643ac112a89a7e52f55"
  }
}

