PATCH /api/2.0/tenders/df482adf4b1a41d38ff9d7f1fd8888c3/complaints/c8d12e22fe7f494788a7673706c44f98?acc_token=7fc0e1e6527b4fd48fe1e419e5a4d08c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "claim"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "claim", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/df482adf4b1a41d38ff9d7f1fd8888c3/complaints/c8d12e22fe7f494788a7673706c44f98/documents/f8bd9dee4bde4674b760c27555646511?download=1452005177d6404eb7622712244ade30", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T11:22:12.423959+02:00", 
        "id": "f8bd9dee4bde4674b760c27555646511", 
        "dateModified": "2016-03-16T11:22:12.423998+02:00"
      }
    ], 
    "description": "complaint description", 
    "title": "complaint title", 
    "dateSubmitted": "2016-03-16T11:22:12.608863+02:00", 
    "complaintID": "UA-2016-03-16-000001.1", 
    "date": "2016-03-16T11:22:12.093155+02:00", 
    "type": "claim", 
    "id": "c8d12e22fe7f494788a7673706c44f98"
  }
}

