POST /api/2.3/tenders/8c7840a135e342abb80894985f570f06/complaints/6d959a6da5e345a895d18a8126c2ff6d/documents?acc_token=8ee0ba0813ab47b792385bb25dfbea7a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 339
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/d33f9cd094064dc287305d9853f9dcef?KeyID=9d50f426&Signature=tpNmbnXlL9HyDKQTYisJ%2B27dnnCy9CJKCIyAsgwpv2BWbD4HBFbWgGdVFYWwCq0lE7mzG4inXm08AycXfqTOCQ%3D%3D", 
    "title": "Complaint_Attachement.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/8c7840a135e342abb80894985f570f06/complaints/6d959a6da5e345a895d18a8126c2ff6d/documents/7ce762e11dcf4b2485eba02b658f8904

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/d33f9cd094064dc287305d9853f9dcef?KeyID=9d50f426&Signature=ZkglGYDIAMToBoH7Tx6ZOtSs1I3AkeeS73KScTH0yHVgHuNAKAx%252Bc2SPClY0XuJbbeIdYX6yzyJY5Io0KkdyDWQAAAAzAAAAMwAAAGYAAAA5AAAAYwAAAGQAAAAwAAAA", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-07-21T17:14:35.523312+03:00", 
    "id": "7ce762e11dcf4b2485eba02b658f8904", 
    "dateModified": "2016-07-21T17:14:35.523348+03:00"
  }
}

