PATCH /api/2.3/tenders/81a0e2e3a6134c28bf7e1e1e128be4ec/complaints/ea2c94e9e49748adbb91c928f6693bd0?acc_token=7091655963f44aafab5d2b507a150b9a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "claim"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "claim", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/2ff55d051e9d4b21b2274a9e5e1b8007?KeyID=425d5e40&Signature=DpIvAm6k7Zj5FYlYi7mq0D3IFg6qoZfqkixZwYbsjGFxEw5xi1iYFv2MUIFYfPM0CdFqRAwzDy91seR%252BauAnDQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-07-25T17:49:16.913990+03:00", 
        "id": "ec4734d8ac6d470fbd6fcd1db5ecc9b9", 
        "dateModified": "2017-07-25T17:49:16.914019+03:00"
      }
    ], 
    "description": "complaint description", 
    "title": "complaint title", 
    "dateSubmitted": "2017-07-25T17:49:16.994558+03:00", 
    "complaintID": "UA-2017-07-25-000001.1", 
    "date": "2017-07-25T17:49:16.998626+03:00", 
    "type": "claim", 
    "id": "ea2c94e9e49748adbb91c928f6693bd0"
  }
}

