PATCH /api/0.12/tenders/34da1cd9ac4343e79f4b163d0a583125/complaints/cf8bef819a69424fbf29768c4385d80e?acc_token=90570714ad74407da1f8ce36c38bdb36 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "satisfied": true
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/34da1cd9ac4343e79f4b163d0a583125/complaints/cf8bef819a69424fbf29768c4385d80e/documents/fd46dbcdf07f4efca75fe7d754af4db3?download=92db6238a7874c198140a3e718814a81", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-02-26T15:08:44.819111+02:00", 
        "id": "fd46dbcdf07f4efca75fe7d754af4db3", 
        "dateModified": "2016-02-26T15:08:44.819162+02:00"
      }
    ], 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "satisfied": true, 
    "tendererAction": "Виправлено неконкурентні умови", 
    "dateAnswered": "2016-02-26T15:08:45.250444+02:00", 
    "tendererActionDate": "2016-02-26T15:08:45.250470+02:00", 
    "dateSubmitted": "2016-02-26T15:08:44.937436+02:00", 
    "date": "2016-02-26T15:08:44.541929+02:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "cf8bef819a69424fbf29768c4385d80e"
  }
}

