PATCH /api/2.3/tenders/6e33b56945624315afece8e75af7193c/complaints/3b36519c7e994663a75935a29c0ddbcf?acc_token=e96bd05708744828a13d48aa6e282cb9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 442
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "answered", 
    "resolutionType": "resolved", 
    "tendererAction": "Виправлено неконкурентні умови", 
    "resolution": "Виправлено неконкурентні умови"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "answered", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/a6eda494834f49f884bc2202b833eb9f?KeyID=1a1ebb61&Signature=HVXI2lfBb%252BTHfNMrSh%2F0cH0hv3YYQ032UDnmB2%252Bu4ntVsOJcqAhScdCfpjFxBUnKOMBTS1co3W35T972IxdpBA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-07-25T17:36:50.767640+03:00", 
        "id": "8ebcc96606e941bc89d601c3d11270d1", 
        "dateModified": "2017-07-25T17:36:50.767661+03:00"
      }
    ], 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "tendererAction": "Виправлено неконкурентні умови", 
    "dateAnswered": "2017-07-25T17:36:50.937282+03:00", 
    "tendererActionDate": "2017-07-25T17:36:50.937311+03:00", 
    "dateSubmitted": "2017-07-25T17:36:50.813612+03:00", 
    "complaintID": "UA-2017-07-25-000001.1", 
    "date": "2017-07-25T17:36:50.939736+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "3b36519c7e994663a75935a29c0ddbcf"
  }
}

