GET /api/0.12/tenders/c0802a5924f74bec8da5ea24fba84b38/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "claim", 
      "documents": [
        {
          "author": "complaint_owner", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/c0802a5924f74bec8da5ea24fba84b38/complaints/6affb68e97da403caba205dba2baf4a0/documents/3a5cab6b8e71408782299d0b11b613cd?download=4d0797bcb60f497bbf319d0c78cc5c25", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2016-02-10T12:41:47.465417+02:00", 
          "id": "3a5cab6b8e71408782299d0b11b613cd", 
          "dateModified": "2016-02-10T12:41:47.465454+02:00"
        }
      ], 
      "description": "complaint description", 
      "title": "complaint title", 
      "author": {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }, 
      "dateSubmitted": "2016-02-10T12:41:47.673523+02:00", 
      "date": "2016-02-10T12:41:47.110293+02:00", 
      "type": "claim", 
      "id": "6affb68e97da403caba205dba2baf4a0"
    }, 
    {
      "status": "claim", 
      "description": "complaint description", 
      "author": {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }, 
      "title": "complaint title", 
      "dateSubmitted": "2016-02-10T12:41:47.869905+02:00", 
      "date": "2016-02-10T12:41:47.868580+02:00", 
      "type": "claim", 
      "id": "f8fd3a52e3d74b3da26705dc01ed0a19"
    }
  ]
}

