GET /api/2.3/tenders/8c7840a135e342abb80894985f570f06/complaints/6d959a6da5e345a895d18a8126c2ff6d HTTP/1.0
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "claim", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/d33f9cd094064dc287305d9853f9dcef?KeyID=9d50f426&Signature=ZkglGYDIAMToBoH7Tx6ZOtSs1I3AkeeS73KScTH0yHVgHuNAKAx%252Bc2SPClY0XuJbbeIdYX6yzyJY5Io0KkdyDWQAAAAzAAAAMwAAAGYAAAA5AAAAYwAAAGQAAAAwAAAA", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-07-21T17:14:35.523312+03:00", 
        "id": "7ce762e11dcf4b2485eba02b658f8904", 
        "dateModified": "2016-07-21T17:14:35.523348+03:00"
      }
    ], 
    "description": "complaint description", 
    "title": "complaint title", 
    "dateSubmitted": "2016-07-21T17:14:35.699969+03:00", 
    "complaintID": "UA-2016-07-21-000001.1", 
    "date": "2016-07-21T17:14:35.403381+03:00", 
    "type": "claim", 
    "id": "6d959a6da5e345a895d18a8126c2ff6d"
  }
}

