POST /api/0.12/tenders/42e7845f7fa64c82bded7abb70fae466/complaints HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 899
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "claim", 
    "title": "complaint title", 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/0.12/tenders/42e7845f7fa64c82bded7abb70fae466/complaints/5d73af8b852b44c58376af3f10363c6a

{
  "access": {
    "token": "e3d23af57cb54084875672dd0d2e538d"
  }, 
  "data": {
    "status": "claim", 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "title": "complaint title", 
    "dateSubmitted": "2016-02-24T11:29:18.660094+02:00", 
    "date": "2016-02-24T11:29:18.658351+02:00", 
    "type": "claim", 
    "id": "5d73af8b852b44c58376af3f10363c6a"
  }
}

