PATCH /api/2.3/tenders/6a4c5d69d2524ac797a4f0e59661ee01/complaints/7969b440b32146a6af6c20844c75f356 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "dateDecision": "2016-05-12T18:08:05.843850+03:00", 
    "documents": [
      {
        "author": "reviewers", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/6a4c5d69d2524ac797a4f0e59661ee01/complaints/7969b440b32146a6af6c20844c75f356/documents/71b3615d7e044fa887e369efbdc9a5b3?download=fd6e4cc79c8f4d2da0e230fbb4671654", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-05-12T18:08:05.612459+03:00", 
        "id": "71b3615d7e044fa887e369efbdc9a5b3", 
        "dateModified": "2016-05-12T18:08:05.612501+03:00"
      }
    ], 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "title": "complaint title", 
    "satisfied": false, 
    "dateEscalated": "2016-05-12T18:08:04.818180+03:00", 
    "dateAnswered": "2016-05-12T18:08:04.609152+03:00", 
    "dateSubmitted": "2016-05-12T18:08:04.404555+03:00", 
    "complaintID": "UA-2016-05-12-000001.3", 
    "date": "2016-05-12T18:08:04.402899+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "7969b440b32146a6af6c20844c75f356"
  }
}

