POST /api/0.12/tenders/c0802a5924f74bec8da5ea24fba84b38/complaints/6affb68e97da403caba205dba2baf4a0/documents?acc_token=83b9e2399f76468dae747bf8a08b1bb5 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 201
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy364970337206$
Host: api-sandbox.openprocurement.org


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/0.12/tenders/c0802a5924f74bec8da5ea24fba84b38/complaints/6affb68e97da403caba205dba2baf4a0/documents/3a5cab6b8e71408782299d0b11b613cd

{
  "data": {
    "author": "complaint_owner", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/c0802a5924f74bec8da5ea24fba84b38/complaints/6affb68e97da403caba205dba2baf4a0/documents/3a5cab6b8e71408782299d0b11b613cd?download=4d0797bcb60f497bbf319d0c78cc5c25", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-02-10T12:41:47.465417+02:00", 
    "id": "3a5cab6b8e71408782299d0b11b613cd", 
    "dateModified": "2016-02-10T12:41:47.465454+02:00"
  }
}

