PATCH /api/2.3/tenders/eeb9177097a14a8c80ca0d1c8b202a00/complaints/04396da5ddf94c86956212086b506a05?acc_token=bc0cb1252c174eb9b87b269f8738db84 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "satisfied": true
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/b2bc1be6296e47c7957e09d66cc760ad?KeyID=a1a42480&Signature=O7DZAAuEuXCCeeLm8KABRkl%252B3%252BlwmfdWWS7Kl7opLE9XeFu4Dft6BeZhzpfsaZe0NLzq9EXA0%2F2UL3%252BqcW8TDWIAAAAyAAAAYgAAAGMAAAAxAAAAYgAAAGUAAAA2AAAA", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-07-21T17:17:50.870513+03:00", 
        "id": "d7959940598f41349b5322613bac7788", 
        "dateModified": "2016-07-21T17:17:50.870543+03:00"
      }
    ], 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "satisfied": true, 
    "tendererAction": "Виправлено неконкурентні умови", 
    "dateAnswered": "2016-07-21T17:17:51.444630+03:00", 
    "tendererActionDate": "2016-07-21T17:17:51.444660+03:00", 
    "dateSubmitted": "2016-07-21T17:17:51.043691+03:00", 
    "complaintID": "UA-2016-07-21-000001.1", 
    "date": "2016-07-21T17:17:51.598031+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "04396da5ddf94c86956212086b506a05"
  }
}

