PATCH /api/0.12/tenders/86a6c78441c84c6aaac17dd007a8832f/complaints/41a54f47e7e343c5bba0993167b1835f?acc_token=560f0a4e27794d8e87b08a915a3a4193 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "pending", 
    "satisfied": false
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "pending", 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "title": "complaint title", 
    "satisfied": false, 
    "dateEscalated": "2016-02-09T18:43:57.880013+02:00", 
    "dateAnswered": "2016-02-09T18:43:57.618138+02:00", 
    "dateSubmitted": "2016-02-09T18:43:56.915092+02:00", 
    "date": "2016-02-09T18:43:56.913757+02:00", 
    "resolution": "Виправлено", 
    "id": "41a54f47e7e343c5bba0993167b1835f"
  }
}

