PATCH /api/2.3/tenders/81a0e2e3a6134c28bf7e1e1e128be4ec/complaints/391e9de1962e4993a7c801059ff21bdc?acc_token=6250bce3d7a3467699b77a6cbfdda573 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 52
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "satisfied": false
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "satisfied": false, 
    "dateAnswered": "2017-07-25T17:49:17.409722+03:00", 
    "dateSubmitted": "2017-07-25T17:49:17.073459+03:00", 
    "complaintID": "UA-2017-07-25-000001.2", 
    "date": "2017-07-25T17:49:17.483977+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "391e9de1962e4993a7c801059ff21bdc"
  }
}

