PATCH /api/2.0/tenders/df482adf4b1a41d38ff9d7f1fd8888c3/complaints/b8540044a51645ae9f13fc14367f1dde HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "invalid"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "invalid", 
    "dateDecision": "2016-03-16T11:22:13.896307+02:00", 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "title": "complaint title", 
    "satisfied": false, 
    "dateEscalated": "2016-03-16T11:22:13.672675+02:00", 
    "dateAnswered": "2016-03-16T11:22:13.451897+02:00", 
    "dateSubmitted": "2016-03-16T11:22:12.796302+02:00", 
    "complaintID": "UA-2016-03-16-000001.2", 
    "date": "2016-03-16T11:22:12.794970+02:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "b8540044a51645ae9f13fc14367f1dde"
  }
}

