PATCH /api/2.0/tenders/d14225f722384c46a31b4e4470b66d8d/complaints/8e70e0851c03497daa8c70c178d45de1 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "declined"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "declined", 
    "dateDecision": "2016-03-16T17:54:15.083063+02:00", 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "title": "complaint title", 
    "satisfied": false, 
    "dateEscalated": "2016-03-16T17:54:14.363402+02:00", 
    "dateAnswered": "2016-03-16T17:54:14.154261+02:00", 
    "dateSubmitted": "2016-03-16T17:54:13.929561+02:00", 
    "complaintID": "UA-2016-03-16-000001.4", 
    "date": "2016-03-16T17:54:13.928260+02:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "8e70e0851c03497daa8c70c178d45de1"
  }
}

