PATCH /api/2.3/tenders/eeb9177097a14a8c80ca0d1c8b202a00/complaints/75548aab79754e1886351dd4d29425b1 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "dateDecision": "2016-07-21T17:17:53.313656+03:00", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "reviewers", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/5edda28875654b50a4c21d5e1fd406d3?KeyID=a1a42480&Signature=E9gM5PLcl9gqPhKL%252B%2FVJ%2FlG2ORbUx0XCXwDJWGAjwOHIuz3lZrkE11pF5wev6PDziSQefI6WlADuw95Ai8R4BDUAAABlAAAAZAAAAGQAAABhAAAAMgAAADgAAAA4AAAA", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-07-21T17:17:53.120349+03:00", 
        "id": "2014c0f3de1945fca7b07dd6b0bc4573", 
        "dateModified": "2016-07-21T17:17:53.120387+03:00"
      }
    ], 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "title": "complaint title", 
    "satisfied": false, 
    "dateEscalated": "2016-07-21T17:17:52.458951+03:00", 
    "dateAnswered": "2016-07-21T17:17:52.307270+03:00", 
    "dateSubmitted": "2016-07-21T17:17:52.148957+03:00", 
    "complaintID": "UA-2016-07-21-000001.3", 
    "date": "2016-07-21T17:17:53.321525+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "75548aab79754e1886351dd4d29425b1"
  }
}

