PATCH /api/0.12/tenders/50596b750c9845d0b87d07a8b6ee0b47/complaints/eb398d46cd6d4c39a4b71802a342e1a0?acc_token=a122c83b42a442ec9a3c12992e41755f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 442
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "answered", 
    "resolutionType": "resolved", 
    "tendererAction": "Виправлено неконкурентні умови", 
    "resolution": "Виправлено неконкурентні умови"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "answered", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/50596b750c9845d0b87d07a8b6ee0b47/complaints/eb398d46cd6d4c39a4b71802a342e1a0/documents/9a48d5f3790a422681c898ad574f20d4?download=a44ffbeb9046430cbc3d364ad5eebd30", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T15:13:03.492574+02:00", 
        "id": "9a48d5f3790a422681c898ad574f20d4", 
        "dateModified": "2016-03-16T15:13:03.492620+02:00"
      }
    ], 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "tendererAction": "Виправлено неконкурентні умови", 
    "dateAnswered": "2016-03-16T15:13:04.165517+02:00", 
    "tendererActionDate": "2016-03-16T15:13:04.165557+02:00", 
    "dateSubmitted": "2016-03-16T15:13:03.691746+02:00", 
    "complaintID": "UA-2016-03-16-000001.1", 
    "date": "2016-03-16T15:13:03.030694+02:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "eb398d46cd6d4c39a4b71802a342e1a0"
  }
}

