PATCH /api/0.12/tenders/6497d563e3fd40a187641dcebd1e27ca/complaints/f16950bde0b34733940e4d9a74cff695 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "invalid"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "invalid", 
    "dateDecision": "2016-03-14T21:28:53.260406+02:00", 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "complaint", 
    "title": "complaint title", 
    "satisfied": false, 
    "dateEscalated": "2016-03-14T21:28:53.025834+02:00", 
    "dateAnswered": "2016-03-14T21:28:52.842599+02:00", 
    "dateSubmitted": "2016-03-14T21:28:52.101304+02:00", 
    "complaintID": "UA-2016-03-14-000001.2", 
    "date": "2016-03-14T21:28:52.099412+02:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "f16950bde0b34733940e4d9a74cff695"
  }
}

