PATCH /api/2.3/tenders/44c7f9d034dd48629bee829830d084ec/cancellations/531904e4e8694ad69fa36107eb2455dd?acc_token=fa100b2f961a46b79f166acd90e1b4bc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/5946308b0d9741019fe1a321c36618db?KeyID=49dd14eb&Signature=6TY%252BkOdTqDFTiq2m2RBf77LA55YdHdp89V%2FrJ2fhl9m44oJep2wr0yM5bnboyilVW5QQePvoEQ5kU2bmh7fNDQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-07-25T17:49:24.588906+03:00", 
        "id": "1afae6f5528b4386b2fe12f770482202", 
        "dateModified": "2017-07-25T17:49:24.588925+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "title": "Notice-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/61fef1c2c3a74a2e86fb7da15546f0f5?KeyID=49dd14eb&Signature=Ge15QtK4A0deeW%2FBRue09gaQgDONq9E8iDAnYLe4rXcZKvKzwAeyN4ZLjsykuSDIA0YFo%252Bwpw5ZAT6b%252BrxlrBw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-07-25T17:49:24.588906+03:00", 
        "id": "1afae6f5528b4386b2fe12f770482202", 
        "dateModified": "2017-07-25T17:49:24.778805+03:00"
      }
    ], 
    "reason": "cancellation reason", 
    "date": "2017-07-25T17:49:24.889813+03:00", 
    "cancellationOf": "tender", 
    "id": "531904e4e8694ad69fa36107eb2455dd"
  }
}

