PATCH /api/2.3/tenders/f3641d0ba0f042e8b49de06d5c7921af/cancellations/8e1908a8ada64ae19ebfa4f2fdd7d873?acc_token=2ef61fa89e8a451ba4149d2f8e31173b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/0a4e09e6e3ac4591a91431586bfec51b?KeyID=459f8ecf&Signature=l7LFxrLX0mB5IFVRX8TZccYKe21EcCllwvCWGH7RdEYrzhMaLep8J9Ae2F5VzMj566FeEGIqh6Cy5wzNVWmPDg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-07-25T17:36:58.123830+03:00", 
        "id": "56d80bbae8ab41e196922d137c87e20d", 
        "dateModified": "2017-07-25T17:36:58.123851+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "title": "Notice-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/d19863828f684b8393cd9907f2bcb84c?KeyID=459f8ecf&Signature=OQ48HntXEVhqTjhaHm0k7h7hcQ1fjG0otkUT%2F31%252Bz4gToAobjILCREgVN14ja5Pa0Y3t3o%2FMjeDLaI7V77fRCw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-07-25T17:36:58.123830+03:00", 
        "id": "56d80bbae8ab41e196922d137c87e20d", 
        "dateModified": "2017-07-25T17:36:58.317900+03:00"
      }
    ], 
    "reason": "cancellation reason", 
    "date": "2017-07-25T17:36:58.421729+03:00", 
    "cancellationOf": "tender", 
    "id": "8e1908a8ada64ae19ebfa4f2fdd7d873"
  }
}

