PATCH /api/0.12/tenders/1e095893c07a48b3a3ec49d4d12510ad/cancellations/5bdca25ed2054881a2d439de4ded2add?acc_token=991badb0337746fc87b8b2367148474f HTTP/1.0
Authorization: Basic dG9rZW46
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "description": "Changed description", 
        "title": "Notice.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/1e095893c07a48b3a3ec49d4d12510ad/cancellations/5bdca25ed2054881a2d439de4ded2add/documents/5a09a91656ee4cad8163ed5a03b9888e?download=90492396eab3419692488f62df8bf7e4", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-02-01T14:21:38.922653+02:00", 
        "id": "5a09a91656ee4cad8163ed5a03b9888e", 
        "dateModified": "2016-02-01T14:21:38.922690+02:00"
      }, 
      {
        "title": "Notice-2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/1e095893c07a48b3a3ec49d4d12510ad/cancellations/5bdca25ed2054881a2d439de4ded2add/documents/5a09a91656ee4cad8163ed5a03b9888e?download=c1f5b99fb6664e87a9a24d607c87695a", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-02-01T14:21:38.922653+02:00", 
        "id": "5a09a91656ee4cad8163ed5a03b9888e", 
        "dateModified": "2016-02-01T14:21:39.235353+02:00"
      }
    ], 
    "reason": "cancellation reason", 
    "date": "2016-02-01T14:21:38.760098+02:00", 
    "cancellationOf": "tender", 
    "id": "5bdca25ed2054881a2d439de4ded2add"
  }
}

