PATCH /api/2.3/tenders/3d59d3514f8d44cbbc946731d71c69e2/questions/becd78c6f9f748b7b363c35f02809b04?acc_token=494217ad83444f8db5850c07715e774d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2017-06-19T18:27:55.359199+03:00", 
    "title": "Калорійність", 
    "date": "2017-06-19T18:27:55.281030+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "becd78c6f9f748b7b363c35f02809b04", 
    "questionOf": "tender"
  }
}

