PATCH /api/0.12/tenders/c734b0da0d05467a82ae248b319b79e1/questions/870ce897fb0d40f9823b7df693d829ad?acc_token=45f71956f89b48eea8ca964dd4bf97fb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність", 
    "date": "2016-03-16T15:13:23.636081+02:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "870ce897fb0d40f9823b7df693d829ad", 
    "questionOf": "tender"
  }
}

