POST /api/2.0/tenders/b75d5f63bf2e42afa5909b1010b04a82/questions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1506
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "author": {
      "contactPoint": {
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк", 
        "email": "soleksuk@gmail.com"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "00137226", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21100", 
        "region": "м. Вінниця", 
        "streetAddress": "вул. Островського, 33", 
        "locality": "м. Вінниця"
      }
    }, 
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.0/tenders/b75d5f63bf2e42afa5909b1010b04a82/questions/f83da6c658a44772bbfc171b3bdf970e

{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "00137226", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Калорійність", 
    "date": "2016-03-16T11:22:30.733704+02:00", 
    "id": "f83da6c658a44772bbfc171b3bdf970e", 
    "questionOf": "tender"
  }
}

