GET /api/2.3/tenders/739500f065ae48a2803388f9b10d3e6e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "auctionUrl": "http://auction-sandbox.openprocurement.org/tenders/739500f065ae48a2803388f9b10d3e6e", 
    "enquiryPeriod": {
      "startDate": "2016-07-07T17:14:32.682336+03:00", 
      "endDate": "2016-07-14T17:14:32.682336+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2016-07-21T17:50:32.682336+03:00", 
    "awardCriteria": "lowestCost", 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "title": "Калорійність", 
        "date": "2016-07-21T17:14:50.784535+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "dd23eaabc5c948bb81b2938838f2d21c", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "739500f065ae48a2803388f9b10d3e6e", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "document description modified", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/2df69e062d094bb4b9ad55c5c33a2594?KeyID=0eb4ace4&Signature=WjcL3%252BnVhegsEKbzwXjphfCr1zhhCBxpVkFpG4OzVFETNSE5wWFEQQZHAupLSR1eHH9NHR8d15%2F0zTLRjHB%2FBDIAAABkAAAAZgAAADYAAAA5AAAAZQAAADAAAAA2AAAA", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-07-21T17:14:50.100511+03:00", 
        "documentType": "technicalSpecifications", 
        "id": "fb6de9e34bb942cb880accd1f89b9abf", 
        "dateModified": "2016-07-21T17:14:50.100546+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/b751b0d7b21e416192bb8edd6c78d621?KeyID=0eb4ace4&Signature=SWAxlH3q1dgdDfUmeQ%2FODFGN6Qs5wOiBhSnsYWMCZQg6DowhfUZ64Uno9niQ%2FEyeBhkoB3lqcfGJljaOExvGC2IAAAA3AAAANQAAADEAAABiAAAAMAAAAGQAAAA3AAAA", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-07-21T17:14:50.482384+03:00", 
        "id": "d988dacddfc54cf6bb1af71773b8cb16", 
        "dateModified": "2016-07-21T17:14:50.482417+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/865cbd3913dc4ed78e7f26742f6613c1?KeyID=0eb4ace4&Signature=52TkSy%2F%252B8w1o0byICaR1nBvReCCVdhA%2FCf%2FWlJwwc5%252B0HCE9dMbefd3eyeUhQ0%2FFkZl1PzEyv07ty3KlS%2FzmBDgAAAA2AAAANQAAAGMAAABiAAAAZAAAADMAAAA5AAAA", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-07-21T17:14:50.482384+03:00", 
        "id": "d988dacddfc54cf6bb1af71773b8cb16", 
        "dateModified": "2016-07-21T17:14:50.645511+03:00"
      }
    ], 
    "title": "футляри до державних нагород", 
    "tenderID": "UA-2016-07-21-000001", 
    "dateModified": "2016-07-21T17:14:52.001502+03:00", 
    "status": "active.auction", 
    "tenderPeriod": {
      "startDate": "2016-07-14T17:14:32.682336+03:00", 
      "endDate": "2016-07-21T17:14:32.682336+03:00"
    }, 
    "auctionPeriod": {
      "startDate": "2016-07-21T17:14:32.682336+03:00", 
      "shouldStartAfter": "2016-07-21T17:14:32.682336+03:00"
    }, 
    "procurementMethodType": "belowThreshold", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-07-23T17:14:32.682336+03:00", 
          "endDate": "2016-07-26T17:14:32.682336+03:00"
        }, 
        "id": "e5750f26ed7145fbaf0d9db217998658", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

