GET /api/2.3/tenders/a4f89b85bdc041f080c73ca5b06ee953 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: public.api.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "auctionUrl": "http://auction-sandbox.openprocurement.org/tenders/a4f89b85bdc041f080c73ca5b06ee953", 
    "enquiryPeriod": {
      "startDate": "2016-05-27T15:29:31.511759+03:00", 
      "endDate": "2016-06-03T15:29:31.511759+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2016-06-10T16:05:31.511759+03:00", 
    "awardCriteria": "lowestCost", 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "title": "Калорійність", 
        "date": "2016-06-10T15:29:50.326138+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "8bbfd1aa8c2e42d49ddf6632232fbb45", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "a4f89b85bdc041f080c73ca5b06ee953", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "description": "document description modified", 
        "title": "Notice.pdf", 
        "url": "https://public.api.openprocurement.org/api/2.3/tenders/a4f89b85bdc041f080c73ca5b06ee953/documents/6d900d7c8e584ff99c734991cfbb7137?download=e498e2079def4c68b93b7f08cbb62743", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-06-10T15:29:49.569824+03:00", 
        "documentType": "technicalSpecifications", 
        "id": "6d900d7c8e584ff99c734991cfbb7137", 
        "dateModified": "2016-06-10T15:29:49.569872+03:00"
      }, 
      {
        "title": "AwardCriteria.pdf", 
        "url": "https://public.api.openprocurement.org/api/2.3/tenders/a4f89b85bdc041f080c73ca5b06ee953/documents/2fc2e39b222b4c74b94738702188424d?download=9ef24d6aa3334caca68d2a0bf740fe09", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-06-10T15:29:49.993070+03:00", 
        "id": "2fc2e39b222b4c74b94738702188424d", 
        "dateModified": "2016-06-10T15:29:49.993111+03:00"
      }, 
      {
        "title": "AwardCriteria-2.pdf", 
        "url": "https://public.api.openprocurement.org/api/2.3/tenders/a4f89b85bdc041f080c73ca5b06ee953/documents/2fc2e39b222b4c74b94738702188424d?download=db7e8c19fdcd4c9d87b5d48a20cbaa78", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-06-10T15:29:49.993070+03:00", 
        "id": "2fc2e39b222b4c74b94738702188424d", 
        "dateModified": "2016-06-10T15:29:50.188364+03:00"
      }
    ], 
    "title": "футляри до державних нагород", 
    "tenderID": "UA-2016-06-10-000001", 
    "dateModified": "2016-06-10T15:29:51.835198+03:00", 
    "status": "active.auction", 
    "tenderPeriod": {
      "startDate": "2016-06-03T15:29:31.511759+03:00", 
      "endDate": "2016-06-10T15:29:31.511759+03:00"
    }, 
    "auctionPeriod": {
      "startDate": "2016-06-10T15:29:31.511759+03:00", 
      "shouldStartAfter": "2016-06-10T15:29:31.511759+03:00"
    }, 
    "procurementMethodType": "belowThreshold", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-06-12T15:29:31.511759+03:00", 
          "endDate": "2016-06-15T15:29:31.511759+03:00"
        }, 
        "id": "bc8a07adf2df4c98aa22e8d598eb06d3", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

