GET /api/2.3/tenders/e2cec5ad28bd4c3a8fe3364457b0ece8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "auctionUrl": "http://auction-sandbox.openprocurement.org/tenders/e2cec5ad28bd4c3a8fe3364457b0ece8", 
    "enquiryPeriod": {
      "startDate": "2016-07-05T16:09:32.635287+03:00", 
      "endDate": "2016-07-12T16:09:32.635287+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2016-07-19T16:45:32.635287+03:00", 
    "awardCriteria": "lowestCost", 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "title": "Калорійність", 
        "date": "2016-07-19T16:09:35.719877+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "da32c429fd724ef2aff91fbfe8b2888c", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "e2cec5ad28bd4c3a8fe3364457b0ece8", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "hash": "00000000000000000000000000000000", 
        "description": "document description modified", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/c3a8138ee4814806839e195d3ff587d4?KeyID=f183a4c7&Signature=15Q%2FnbKz39ltZexBN1I3ukGA9jv1qPsje54QMno9N%252BIfqhd1%2FRVr99PuE5FrDgf%2FnBOswbpmOyb4KrI7AY6WBGMAAAAzAAAAYQAAADgAAAAxAAAAMwAAADgAAABlAAAA", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-07-19T16:09:34.974354+03:00", 
        "documentType": "technicalSpecifications", 
        "id": "37294fd61f974766b01b673ebe845db0", 
        "dateModified": "2016-07-19T16:09:34.974395+03:00"
      }, 
      {
        "hash": "00000000000000000000000000000000", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/1fc7192d23af416bab224a5ab659bde0?KeyID=f183a4c7&Signature=oxy5lRBGC5NzvVYdWWIxIHBJyAn%252BYVZ2tImTUdHUTGjUADE45RdyBaIsrB4S1uCOcm7ow9vw2m2%2FzzJEaMVkBzEAAABmAAAAYwAAADcAAAAxAAAAOQAAADIAAABkAAAA", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-07-19T16:09:35.395268+03:00", 
        "id": "6006d472bbd54c29831b66c872ef2cd0", 
        "dateModified": "2016-07-19T16:09:35.395310+03:00"
      }, 
      {
        "hash": "00000000000000000000000000000000", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/8b4db4990d424c93ab0359bb8e68e197?KeyID=f183a4c7&Signature=b%2FgqVyRoKyHdmgRvlbK7UoZb5HgoY3SCZ9HxZejWr%252Bo8%252BvSXlP9hrdGoIS2c3yQoGMn9rFWKHlojLhnMk00QBzgAAABiAAAANAAAAGQAAABiAAAANAAAADkAAAA5AAAA", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-07-19T16:09:35.395268+03:00", 
        "id": "6006d472bbd54c29831b66c872ef2cd0", 
        "dateModified": "2016-07-19T16:09:35.590270+03:00"
      }
    ], 
    "title": "футляри до державних нагород", 
    "tenderID": "UA-2016-07-19-000001", 
    "dateModified": "2016-07-19T16:09:37.076411+03:00", 
    "status": "active.auction", 
    "tenderPeriod": {
      "startDate": "2016-07-12T16:09:32.635287+03:00", 
      "endDate": "2016-07-19T16:09:32.635287+03:00"
    }, 
    "auctionPeriod": {
      "startDate": "2016-07-19T16:09:32.635287+03:00", 
      "shouldStartAfter": "2016-07-19T16:09:32.635287+03:00"
    }, 
    "procurementMethodType": "belowThreshold", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-07-21T16:09:32.635287+03:00", 
          "endDate": "2016-07-24T16:09:32.635287+03:00"
        }, 
        "id": "e93d8af8630c4697a276e344b2bc61c2", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

