GET /api/0.12/tenders/1e095893c07a48b3a3ec49d4d12510ad/bids/eff32062a78a4b898bc8b1a3e03fa043?acc_token=f679d168c42342809cbffd98e57467e9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "date": "2016-02-01T14:21:37.332676+02:00", 
    "documents": [
      {
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/1e095893c07a48b3a3ec49d4d12510ad/bids/eff32062a78a4b898bc8b1a3e03fa043/documents/7395954550f047fa99c8fb31406830ac?download=cddfc409fc4a406f9fc3dc06ed95a656", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-02-01T14:21:37.472640+02:00", 
        "id": "7395954550f047fa99c8fb31406830ac", 
        "dateModified": "2016-02-01T14:21:37.472686+02:00"
      }
    ], 
    "id": "eff32062a78a4b898bc8b1a3e03fa043", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ]
  }
}

