GET /api/0.12/tenders/c734b0da0d05467a82ae248b319b79e1/bids/d8a5f816dbef4b09be478237ac3251ce?acc_token=3ed5fcbcf7614b45b6e6e1e20cc2b0a9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "documents": [
      {
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/c734b0da0d05467a82ae248b319b79e1/bids/d8a5f816dbef4b09be478237ac3251ce/documents/36427cd33524401bbb4830a6fd7307ef?download=93c6f7f215414e4c846b4ffc6ff33a76", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T15:13:24.497872+02:00", 
        "id": "36427cd33524401bbb4830a6fd7307ef", 
        "dateModified": "2016-03-16T15:13:24.497922+02:00"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2016-03-16T15:13:24.165239+02:00", 
    "id": "d8a5f816dbef4b09be478237ac3251ce", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/c734b0da0d05467a82ae248b319b79e1?key_for_bid=d8a5f816dbef4b09be478237ac3251ce", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }
  }
}

