GET /api/0.12/tenders/d43c874272844fab88e7f2681b304252/bids/996c243258784b6da23d3cd24f7a2f96?acc_token=aeee2e4aa9014dada87ceff37894892f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "date": "2016-03-14T21:29:10.161618+02:00", 
    "documents": [
      {
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/d43c874272844fab88e7f2681b304252/bids/996c243258784b6da23d3cd24f7a2f96/documents/0e292de155974b33b1ed7f2d251d90df?download=bcc21a3d8f274fe39d33ee99fadf400a", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-14T21:29:10.311838+02:00", 
        "id": "0e292de155974b33b1ed7f2d251d90df", 
        "dateModified": "2016-03-14T21:29:10.311879+02:00"
      }
    ], 
    "id": "996c243258784b6da23d3cd24f7a2f96", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ]
  }
}

