GET /api/0.12/tenders/c5cc24b1753140aebf0dfe98297fdd08/bids/25606420a60a4188a7c74b4f727c98d6?acc_token=b054e527658c4570bd2054f63ea5396c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "date": "2016-02-09T18:44:11.178678+02:00", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "id": "25606420a60a4188a7c74b4f727c98d6", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/c5cc24b1753140aebf0dfe98297fdd08?key_for_bid=25606420a60a4188a7c74b4f727c98d6", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}

