GET /api/2.0/tenders/b75d5f63bf2e42afa5909b1010b04a82/bids/3992d28507964bb5bfb51ff0a451d4bb?acc_token=9db2d472115e4fb2809762ca0111bdb8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "documents": [
      {
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/b75d5f63bf2e42afa5909b1010b04a82/bids/3992d28507964bb5bfb51ff0a451d4bb/documents/cea9a2680276416597726098b0beb97f?download=f3d7a0dc5a584d10950abadc3fe528e8", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T11:22:31.543973+02:00", 
        "id": "cea9a2680276416597726098b0beb97f", 
        "dateModified": "2016-03-16T11:22:31.544012+02:00"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2016-03-16T11:22:31.332846+02:00", 
    "id": "3992d28507964bb5bfb51ff0a451d4bb", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/b75d5f63bf2e42afa5909b1010b04a82?key_for_bid=3992d28507964bb5bfb51ff0a451d4bb"
  }
}

