GET /api/2.3/tenders/3302890835e145a28b553588bc630590/bids/840dfb0ce72b4dea81c31b6f143aa94d?acc_token=cf2e0637c39f41598289ed6a36867ee9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "documents": [
      {
        "hash": "00000000000000000000000000000000", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/3302890835e145a28b553588bc630590/bids/840dfb0ce72b4dea81c31b6f143aa94d/documents/8db14731123740e7a15dbe9cb7fa36c0?download=e6450719a4dc46f2bdbb0e0f2bfc40de", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-07-20T17:17:35.098560+03:00", 
        "id": "8db14731123740e7a15dbe9cb7fa36c0", 
        "dateModified": "2016-07-20T17:17:35.098593+03:00"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2016-07-20T17:17:34.974822+03:00", 
    "id": "840dfb0ce72b4dea81c31b6f143aa94d", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/3302890835e145a28b553588bc630590?key_for_bid=840dfb0ce72b4dea81c31b6f143aa94d"
  }
}

