GET /api/2.3/tenders/a4f89b85bdc041f080c73ca5b06ee953/bids/7f89957a3dbb43ccbddb1b821b0fff3d?acc_token=c53478d3b8a4462b87416156a5dc206d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2016-06-10T15:29:51.357653+03:00", 
    "id": "7f89957a3dbb43ccbddb1b821b0fff3d", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/a4f89b85bdc041f080c73ca5b06ee953?key_for_bid=7f89957a3dbb43ccbddb1b821b0fff3d"
  }
}

