$ http -j PATCH https://api-sandbox.openprocurement.org/api/0/tenders/779630aecd87417097dcfb48871b6990 data:={"status":"cancelled"}
PATCH /api/0/tenders/779630aecd87417097dcfb48871b6990 HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "data": {
        "status": "cancelled"
    }
}

HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{
    "data": {
        "dateModified": "2014-12-01T17:39:23.440187+02:00", 
        "enquiryPeriod": {
            "startDate": "2014-12-01T17:39:21.504836+02:00"
        }, 
        "id": "779630aecd87417097dcfb48871b6990", 
        "status": "cancelled", 
        "tenderID": "UA-779630aecd87417097dcfb48871b6990"
    }
}
