$ http -j POST https://api-sandbox.openprocurement.org/api/0/tenders/c0c01003785344829136c3890ddf8192/complaints data:=@./complaint.json
POST /api/0/tenders/c0c01003785344829136c3890ddf8192/complaints HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "data": {
        "author": {
            "address": {
                "countryName": "Україна", 
                "locality": "м. Вінниця", 
                "postalCode": "21100", 
                "region": "м. Вінниця", 
                "streetAddress": "вул. Островського, 33"
            }, 
            "contactPoint": {
                "email": "soleksuk@gmail.com", 
                "name": "Сергій Олексюк", 
                "telephone": "+380 (432) 21-69-30"
            }, 
            "identifier": {
                "id": "13313462", 
                "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
                "scheme": "https://ns.openprocurement.org/ua/edrpou", 
                "uri": "http://sch10.edu.vn.ua/"
            }, 
            "name": "ДКП «Школяр»"
        }, 
        "status": "claim",
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "title": "Недостатньо інформації"
    }
}

HTTP/1.1 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/0/tenders/c0c01003785344829136c3890ddf8192/complaints/8e17d36ac7a049b6889ed2e01687db88

{
    "access": {
        "token": "981981131c94413faf532e0af13a8cc5"
    }, 
    "data": {
        "author": {
            "address": {
                "countryName": "Україна", 
                "locality": "м. Вінниця", 
                "postalCode": "21100", 
                "region": "м. Вінниця", 
                "streetAddress": "вул. Островського, 33"
            }, 
            "contactPoint": {
                "email": "soleksuk@gmail.com", 
                "name": "Сергій Олексюк", 
                "telephone": "+380 (432) 21-69-30"
            }, 
            "identifier": {
                "id": "13313462", 
                "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
                "scheme": "https://ns.openprocurement.org/ua/edrpou", 
                "uri": "http://sch10.edu.vn.ua/"
            }, 
            "name": "ДКП «Школяр»"
        }, 
        "date": "2014-12-02T22:35:25.198141+02:00", 
        "dateSubmitted": "2014-12-02T22:35:25.198141+02:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "id": "8e17d36ac7a049b6889ed2e01687db88", 
        "status": "claim", 
        "title": "Недостатньо інформації"
    }
}
