PATCH /api/2.0/tenders/befb9d3f7d284391a71619c9f5681d04/awards/f598dca97ce34d5bb6fedb8af04f0325?acc_token=4da834b414ca4cc59f88625f8af79aa3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "complaintPeriod": {
      "startDate": "2016-03-16T12:11:46.969587+02:00", 
      "endDate": "2016-03-17T12:11:47.252258+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "bid_id": "17893174e39048039fa113cc4ea9952a", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-03-16T12:11:46.969909+02:00", 
    "id": "f598dca97ce34d5bb6fedb8af04f0325"
  }
}

