POST /api/0.12/tenders/1e095893c07a48b3a3ec49d4d12510ad/awards?acc_token=991badb0337746fc87b8b2367148474f HTTP/1.0
Authorization: Basic dG9rZW46
Content-Length: 884
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "pending", 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "eff32062a78a4b898bc8b1a3e03fa043"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/0.12/tenders/1e095893c07a48b3a3ec49d4d12510ad/awards/b3c9665f8e874cde894c9e711af1a689

{
  "data": {
    "status": "pending", 
    "complaintPeriod": {
      "startDate": "2016-02-01T14:21:38.602841+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "eff32062a78a4b898bc8b1a3e03fa043", 
    "date": "2016-02-01T14:21:38.601664+02:00", 
    "id": "b3c9665f8e874cde894c9e711af1a689"
  }
}

