POST /api/0.12/tenders?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 4133
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "features": [
      {
        "code": "OCDS-123454-AIR-INTAKE", 
        "description": "Ефективна потужність всмоктування пилососа, в ватах (аероватах)", 
        "title": "Потужність всмоктування", 
        "enum": [
          {
            "value": 0.1, 
            "title": "До 1000 Вт"
          }, 
          {
            "value": 0.15, 
            "title": "Більше 1000 Вт"
          }
        ], 
        "title_en": "Air Intake", 
        "relatedItem": "cedc919fed994479b0f632fb02469301", 
        "featureOf": "item"
      }, 
      {
        "code": "OCDS-123454-YEARS", 
        "description": "Кількість років, які організація учасник працює на ринку", 
        "title": "Років на ринку", 
        "enum": [
          {
            "value": 0.05, 
            "title": "До 3 років"
          }, 
          {
            "value": 0.1, 
            "title": "Більше 3 років, менше 5 років"
          }, 
          {
            "value": 0.15, 
            "title": "Більше 5 років"
          }
        ], 
        "title_en": "Years trading", 
        "featureOf": "tenderer"
      }
    ], 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "enquiryPeriod": {
      "endDate": "2016-02-16T18:43:53.657905"
    }, 
    "title_en": "Cases with state awards", 
    "value": {
      "currency": "UAH", 
      "amount": 500
    }, 
    "mode": "test", 
    "procurementMethodType": "belowThreshold", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "title_ru": "футляры к государственным наградам", 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "id": "44617100-9", 
          "description": "Cartons"
        }, 
        "description_en": "Cases with state awards", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "description_ru": "футляры к государственным наградам", 
        "id": "cedc919fed994479b0f632fb02469301", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "tenderPeriod": {
      "endDate": "2016-02-23T18:43:53.657905"
    }
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/0.12/tenders/1c123070ddee4b368649afe2303ea450

{
  "access": {
    "token": "a296282419d049f782e91d540e75a379"
  }, 
  "data": {
    "procurementMethod": "open", 
    "status": "active.enquiries", 
    "tenderID": "UA-2016-02-09-000002", 
    "tenderPeriod": {
      "startDate": "2016-02-16T18:43:53.657905+02:00", 
      "endDate": "2016-02-23T18:43:53.657905+02:00"
    }, 
    "title": "[ТЕСТУВАННЯ] футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "description_en": "Cases with state awards", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "description_ru": "футляры к государственным наградам", 
        "id": "cedc919fed994479b0f632fb02469301", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "procurementMethodType": "belowThreshold", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "awardCriteria": "lowestCost", 
    "next_check": "2016-02-16T18:43:53.657905+02:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "title_ru": "[ТЕСТИРОВАНИЕ] футляры к государственным наградам", 
    "enquiryPeriod": {
      "startDate": "2016-02-09T18:44:08.161557+02:00", 
      "endDate": "2016-02-16T18:43:53.657905+02:00"
    }, 
    "owner": "broker", 
    "dateModified": "2016-02-09T18:44:08.169517+02:00", 
    "mode": "test", 
    "title_en": "[TESTING] Cases with state awards", 
    "id": "1c123070ddee4b368649afe2303ea450", 
    "features": [
      {
        "code": "OCDS-123454-AIR-INTAKE", 
        "description": "Ефективна потужність всмоктування пилососа, в ватах (аероватах)", 
        "title": "Потужність всмоктування", 
        "enum": [
          {
            "value": 0.1, 
            "title": "До 1000 Вт"
          }, 
          {
            "value": 0.15, 
            "title": "Більше 1000 Вт"
          }
        ], 
        "title_en": "Air Intake", 
        "relatedItem": "cedc919fed994479b0f632fb02469301", 
        "featureOf": "item"
      }, 
      {
        "code": "OCDS-123454-YEARS", 
        "description": "Кількість років, які організація учасник працює на ринку", 
        "title": "Років на ринку", 
        "enum": [
          {
            "value": 0.05, 
            "title": "До 3 років"
          }, 
          {
            "value": 0.1, 
            "title": "Більше 3 років, менше 5 років"
          }, 
          {
            "value": 0.15, 
            "title": "Більше 5 років"
          }
        ], 
        "title_en": "Years trading", 
        "featureOf": "tenderer"
      }
    ]
  }
}

