$ http -j POST https://api-sandbox.openprocurement.org/api/0/tenders data:=@./school-tender.json
POST /api/0/tenders HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "data": {
        "procuringEntity": {
            "address": {
                "countryName": "Україна", 
                "locality": "м. Вінниця", 
                "postalCode": "21027", 
                "region": "м. Вінниця", 
                "streetAddress": "вул. Стахурського. 22"
            }, 
            "identifier": {
                "id": "21725150", 
                "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\"", 
                "scheme": "https://ns.openprocurement.org/ua/edrpou", 
                "uri": "http://sch10.edu.vn.ua/"
            }, 
            "name": "ЗОСШ #10 м.Вінниці"
        }
    }
}

HTTP/1.1 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/0/tenders/327c00d16cff4c37be5bd4915cdff8a3

{
    "access": {
        "token": "4668a63ccfd443e8b848e856952e9a2b"
    }, 
    "data": {
        "dateModified": "2014-12-01T17:39:25.289180+02:00", 
        "enquiryPeriod": {
            "startDate": "2014-12-01T17:39:25.289180+02:00"
        }, 
        "id": "327c00d16cff4c37be5bd4915cdff8a3", 
        "procuringEntity": {
            "address": {
                "countryName": "Україна", 
                "locality": "м. Вінниця", 
                "postalCode": "21027", 
                "region": "м. Вінниця", 
                "streetAddress": "вул. Стахурського. 22"
            }, 
            "identifier": {
                "id": "21725150", 
                "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\"", 
                "scheme": "https://ns.openprocurement.org/ua/edrpou", 
                "uri": "http://sch10.edu.vn.ua/"
            }, 
            "name": "ЗОСШ #10 м.Вінниці"
        }, 
        "status": "active.enquiries", 
        "tenderID": "UA-327c00d16cff4c37be5bd4915cdff8a3"
    }
}
