GET /api/2.3/tenders/abd7bd35532d4b2999f85bc87c80d23f/questions/f502e909004e419281f56fb381a80340 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2017-06-24T18:00:37.963146+03:00", 
    "title": "Калорійність", 
    "date": "2017-06-24T18:00:37.888082+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "f502e909004e419281f56fb381a80340", 
    "questionOf": "tender"
  }
}

