GET /api/2.3/tenders/cf18944f39e64959b68050125c8d0ce5/questions/2c47a0fd995b4f14ba913098d7a20998 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність", 
    "date": "2016-05-12T18:08:21.826962+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "2c47a0fd995b4f14ba913098d7a20998", 
    "questionOf": "tender"
  }
}

