GET /api/0.12/tenders HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "next_page": {
    "path": "/api/0.12/tenders?offset=2016-02-10T12%3A41%3A58.483119%2B02%3A00", 
    "uri": "http://api-sandbox.openprocurement.org/api/0.12/tenders?offset=2016-02-10T12%3A41%3A58.483119%2B02%3A00", 
    "offset": "2016-02-10T12:41:58.483119+02:00"
  }, 
  "data": [
    {
      "id": "e98e2eb727c645d4b04ff7a56fef272f", 
      "dateModified": "2016-02-10T12:41:58.483119+02:00"
    }
  ]
}

