GET /api/2.3/tenders HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "next_page": {
    "path": "/api/2.3/tenders?offset=", 
    "uri": "http://api-sandbox.openprocurement.org/api/2.3/tenders?offset=", 
    "offset": ""
  }, 
  "data": []
}

