GET /api/0.12/tenders/ce536c5f46d543ec81ffa86ce4c77c8b/questions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "description": "Просимо додати таблицю потрібної калорійності харчування", 
      "title": "Калорійність", 
      "date": "2016-03-18T18:48:03.398193+02:00", 
      "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
      "id": "241f4ab8df634f23a11f61fe2074a78f", 
      "questionOf": "tender"
    }
  ]
}

