GET /api/2.3/tenders/a4f89b85bdc041f080c73ca5b06ee953/questions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "description": "Просимо додати таблицю потрібної калорійності харчування", 
      "title": "Калорійність", 
      "date": "2016-06-10T15:29:50.326138+03:00", 
      "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
      "id": "8bbfd1aa8c2e42d49ddf6632232fbb45", 
      "questionOf": "tender"
    }
  ]
}

