$ http -j https://api-sandbox.openprocurement.org/api/0/tenders/327c00d16cff4c37be5bd4915cdff8a3/questions
GET /api/0/tenders/327c00d16cff4c37be5bd4915cdff8a3/questions HTTP/1.1
Content-Type: application/json; charset=utf-8



HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{
    "data": [
        {
            "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
            "date": "2014-12-01T17:39:35.616161+02:00", 
            "description": "Просимо додати таблицю потрібної калорійності харчування по місяцях", 
            "id": "74fb1c83ec7549e0abd7284e05287b8b", 
            "title": "Калорійність по місяцях"
        }
    ]
}
