PATCH /api/2.3/tenders/b74c14bbee6f44a9a0c8408c13a4c1a8/cancellations/8c62294d8c5c43fc8cd075143ef772e7/documents/6ea3622b38b04db882be9772c0fcde6f?acc_token=6241dc3adcf04c33b4f86f08e8e6e591 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "description": "Changed description"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/80d2edd6bcdd4dd999999569a90f2042?KeyID=ef5aa287&Signature=XFfRbNHJU%2FwzJGSSvCCqTdKaIzK%2FmiqAV5ZWaftiYd0QLKTTo9xrjJhxxZIGJjkbxo5PQaolSN5DjCmL3OOhAjgAAAAwAAAAZAAAADIAAABlAAAAZAAAAGQAAAA2AAAA", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-07-21T17:18:11.002943+03:00", 
    "id": "6ea3622b38b04db882be9772c0fcde6f", 
    "dateModified": "2016-07-21T17:18:11.002973+03:00"
  }
}

