PATCH /api/2.0/tenders/b75d5f63bf2e42afa5909b1010b04a82/cancellations/c4f43f59a2ca4cfdba6775a6c435524c/documents/657b1fe45f6e45689af74671e787c1ba?acc_token=dd63600df44a422eb7bdb729c9269624 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "description": "Changed description"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "description": "Changed description", 
    "title": "Notice.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/b75d5f63bf2e42afa5909b1010b04a82/cancellations/c4f43f59a2ca4cfdba6775a6c435524c/documents/657b1fe45f6e45689af74671e787c1ba?download=0228bbcff61f4d76934fd89e9736e760", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-03-16T11:22:35.757448+02:00", 
    "id": "657b1fe45f6e45689af74671e787c1ba", 
    "dateModified": "2016-03-16T11:22:35.757487+02:00"
  }
}

