$ http -j PATCH http://api-sandbox.openprocurement.org/api/0/tenders/b65397298b2e4d9b987adf576d13b9f5 data:=@./school-tender-patch.json
PATCH /api/0/tenders/b65397298b2e4d9b987adf576d13b9f5 HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "data": {
        "enquiryPeriod": {
            "endDate": "2015-05-29T00:00:00"
        }, 
        "itemsToBeProcured": [
            {
                "additionalClassification": [
                    {
                        "description": "Послуги шкільних їдалень", 
                        "id": "55.51.10.300", 
                        "scheme": "ДКПП"
                    }
                ], 
                "description": "Послуги шкільних їдалень", 
                "primaryClassification": {
                    "description": "Послуги з харчування у школах", 
                    "id": "55523100-3", 
                    "scheme": "CPV"
                }, 
                "quantity": 5, 
                "unitOfMeasure": "item"
            }
        ], 
        "tenderPeriod": {
            "endDate": "2015-06-07T10:00:00", 
            "startDate": "2014-11-03T00:00:00"
        }, 
        "totalValue": {
            "amount": 50000, 
            "currency": "UAH", 
            "valueAddedTaxIncluded": true
        }
    }
}

HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{
    "data": {
        "enquiryPeriod": {
            "endDate": "2015-05-29T00:00:00.000000", 
            "startDate": null
        }, 
        "id": "b65397298b2e4d9b987adf576d13b9f5", 
        "itemsToBeProcured": [
            {
                "additionalClassification": [
                    {
                        "description": "Послуги шкільних їдалень", 
                        "id": "55.51.10.300", 
                        "scheme": "ДКПП", 
                        "uri": null
                    }
                ], 
                "description": "Послуги шкільних їдалень", 
                "primaryClassification": {
                    "description": "Послуги з харчування у школах", 
                    "id": "55523100-3", 
                    "scheme": "CPV", 
                    "uri": null
                }, 
                "quantity": 5, 
                "unitOfMeasure": "item", 
                "valuePerUnit": null
            }
        ], 
        "modified": "2014-11-08T00:09:31.090792", 
        "procuringEntity": {
            "address": {
                "countryName": "Україна", 
                "locality": "м. Вінниця", 
                "postalCode": "21027", 
                "region": "м. Вінниця", 
                "streetAddress": "вул. Стахурського. 22"
            }, 
            "id": {
                "name": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\"", 
                "scheme": "https://ns.openprocurement.org/ua/edrpou", 
                "uid": "21725150", 
                "uri": "http://sch10.edu.vn.ua/"
            }
        }, 
        "status": "enquiries", 
        "tenderID": "UA-b65397298b2e4d9b987adf576d13b9f5", 
        "tenderPeriod": {
            "endDate": "2015-06-07T10:00:00.000000", 
            "startDate": "2014-11-03T00:00:00.000000"
        }, 
        "totalValue": {
            "amount": 50000.0, 
            "currency": "UAH", 
            "valueAddedTaxIncluded": true
        }
    }
}
