POST /api/2.3/tenders/739500f065ae48a2803388f9b10d3e6e/cancellations?acc_token=6a42c69b4d5849aeaa171f6119fb1b9c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "reason": "cancellation reason"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/739500f065ae48a2803388f9b10d3e6e/cancellations/e53e8fb9b6c7421d927ca306efd50a83

{
  "data": {
    "date": "2016-07-21T17:14:55.037710+03:00", 
    "status": "pending", 
    "reason": "cancellation reason", 
    "cancellationOf": "tender", 
    "id": "e53e8fb9b6c7421d927ca306efd50a83"
  }
}

