POST /api/2.0/tenders/3bbde406592c4c82b392442cc7affbbc/cancellations?acc_token=e63fecce92854fc38bb5c3f5d3df15c2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "reason": "cancellation reason"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.0/tenders/3bbde406592c4c82b392442cc7affbbc/cancellations/fdec9b34201d4372afac254fc0502bda

{
  "data": {
    "date": "2016-03-16T14:12:06.828920+02:00", 
    "status": "pending", 
    "reason": "cancellation reason", 
    "cancellationOf": "tender", 
    "id": "fdec9b34201d4372afac254fc0502bda"
  }
}

