POST /api/2.3/tenders/f860f9fe94574d729c87f81cea222b46/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1377
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "documents": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/a6a010ec141e4c2b8d6197d3f1c68f0f?KeyID=661750a8&Signature=%2BFDxLL7Ss52mLPP%2Fk6dvrpXNgmSSOAbMcGqLelmLr4TekhvK%2F5oXR5%2BidbLq9OqQpkfjF8VUeLCrsHS%2BmOfBBQ%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }, 
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/ad2e984d49f541689ca0ed155adef063?KeyID=661750a8&Signature=Rli79c00TqvfjP6fnbhHdDnqiniIJcc8I2%2Bc%2BouweWabNxLBajvq3r8ddf3jyaSjD3F5xqYPBkqnQUyawbdIDw%3D%3D", 
        "title": "Proposal_part2.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ],
    "value": {
      "amount": 499
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк", 
          "email": "aagt@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 34", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/f860f9fe94574d729c87f81cea222b46/bids/3310692784ce42bfb7cd8fac8add180f

{
  "access": {
    "token": "cbef7d4282894ae9b51eae637d97b2c6"
  }, 
  "data": {
    "date": "2016-07-21T17:18:07.358915+03:00", 
    "status": "active",
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part1.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/f860f9fe94574d729c87f81cea222b46/bids/3310692784ce42bfb7cd8fac8add180f/documents/f872e90507f14f48bca386fe0eadf502?download=a6a010ec141e4c2b8d6197d3f1c68f0f", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-06-24T18:05:47.259310+03:00", 
        "id": "f872e90507f14f48bca386fe0eadf502", 
        "dateModified": "2017-06-24T18:05:47.259343+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/f860f9fe94574d729c87f81cea222b46/bids/3310692784ce42bfb7cd8fac8add180f/documents/a6cf8c26526e4ccb94e23fa979c3cd58?download=ad2e984d49f541689ca0ed155adef063", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-06-24T18:05:47.260182+03:00", 
        "id": "a6cf8c26526e4ccb94e23fa979c3cd58", 
        "dateModified": "2017-06-24T18:05:47.260213+03:00"
      }
    ],
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2017-06-24T18:05:47.258272+03:00", 
    "id": "3310692784ce42bfb7cd8fac8add180f"
  }
}

