$ http -j POST https://api-sandbox.openprocurement.org/api/0/tenders/327c00d16cff4c37be5bd4915cdff8a3/bids data:=@./catering-bid.json
POST /api/0/tenders/327c00d16cff4c37be5bd4915cdff8a3/bids HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "data": {
        "tenderers": [
            {
                "address": {
                    "countryName": "Україна", 
                    "locality": "м. Вінниця", 
                    "postalCode": "21100", 
                    "region": "м. Вінниця", 
                    "streetAddress": "вул. Островського, 33"
                }, 
                "contactPoint": {
                    "email": "soleksuk@gmail.com", 
                    "name": "Сергій Олексюк", 
                    "telephone": "+380 (432) 21-69-30"
                }, 
                "identifier": {
                    "id": "13313462", 
                    "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
                    "scheme": "https://ns.openprocurement.org/ua/edrpou", 
                    "uri": "http://sch10.edu.vn.ua/"
                }, 
                "name": "ДКП «Школяр»"
            }
        ], 
        "value": {
            "amount": 475000
        }
    }
}

HTTP/1.1 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/0/tenders/327c00d16cff4c37be5bd4915cdff8a3/bids/9b2c1ec83e1646edb2ce6056d653d390

{
    "data": {
        "date": "2014-12-01T17:39:39.940339+02:00", 
        "id": "9b2c1ec83e1646edb2ce6056d653d390", 
        "tenderers": [
            {
                "address": {
                    "countryName": "Україна", 
                    "locality": "м. Вінниця", 
                    "postalCode": "21100", 
                    "region": "м. Вінниця", 
                    "streetAddress": "вул. Островського, 33"
                }, 
                "contactPoint": {
                    "email": "soleksuk@gmail.com", 
                    "name": "Сергій Олексюк", 
                    "telephone": "+380 (432) 21-69-30"
                }, 
                "identifier": {
                    "id": "13313462", 
                    "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
                    "scheme": "https://ns.openprocurement.org/ua/edrpou", 
                    "uri": "http://sch10.edu.vn.ua/"
                }, 
                "name": "ДКП «Школяр»"
            }
        ], 
        "value": {
            "amount": 475000.0, 
            "currency": "UAH", 
            "valueAddedTaxIncluded": true
        }
    }
}
