PATCH /api/2.3/tenders/e2cec5ad28bd4c3a8fe3364457b0ece8?acc_token=9af449b524a647ff9b25b441219a2a7d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 57
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "guarantee": {
      "currency": "USD", 
      "amount": 8
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "status": "active.enquiries", 
    "tenderID": "UA-2016-07-19-000001", 
    "tenderPeriod": {
      "startDate": "2016-07-26T16:09:32.635287+03:00", 
      "endDate": "2016-08-03T16:09:44.375868+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-07-21T16:09:32.635287+03:00", 
          "endDate": "2016-07-24T16:09:32.635287+03:00"
        }, 
        "id": "e93d8af8630c4697a276e344b2bc61c2", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "procurementMethodType": "belowThreshold", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2016-07-26T16:09:32.635287+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "enquiryPeriod": {
      "startDate": "2016-07-19T16:09:33.804599+03:00", 
      "endDate": "2016-07-26T16:09:32.635287+03:00"
    }, 
    "owner": "broker", 
    "dateModified": "2016-07-19T16:09:34.654461+03:00", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "id": "e2cec5ad28bd4c3a8fe3364457b0ece8", 
    "awardCriteria": "lowestCost"
  }
}

