GET /api/2.3/tenders/739500f065ae48a2803388f9b10d3e6e/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description modified", 
      "title": "Notice.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/2df69e062d094bb4b9ad55c5c33a2594?KeyID=0eb4ace4&Signature=WjcL3%252BnVhegsEKbzwXjphfCr1zhhCBxpVkFpG4OzVFETNSE5wWFEQQZHAupLSR1eHH9NHR8d15%2F0zTLRjHB%2FBDIAAABkAAAAZgAAADYAAAA5AAAAZQAAADAAAAA2AAAA", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-07-21T17:14:50.100511+03:00", 
      "documentType": "technicalSpecifications", 
      "id": "fb6de9e34bb942cb880accd1f89b9abf", 
      "dateModified": "2016-07-21T17:14:50.100546+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "AwardCriteria-2.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/865cbd3913dc4ed78e7f26742f6613c1?KeyID=0eb4ace4&Signature=52TkSy%2F%252B8w1o0byICaR1nBvReCCVdhA%2FCf%2FWlJwwc5%252B0HCE9dMbefd3eyeUhQ0%2FFkZl1PzEyv07ty3KlS%2FzmBDgAAAA2AAAANQAAAGMAAABiAAAAZAAAADMAAAA5AAAA", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-07-21T17:14:50.482384+03:00", 
      "id": "d988dacddfc54cf6bb1af71773b8cb16", 
      "dateModified": "2016-07-21T17:14:50.645511+03:00"
    }
  ]
}

