PATCH /api/2.3/tenders/b74c14bbee6f44a9a0c8408c13a4c1a8/contracts/7806df6a0ceb42cc9c7fff929ed03024?acc_token=6241dc3adcf04c33b4f86f08e8e6e591 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 106
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "period": {
      "startDate": "2016-07-21T17:17:48.208303", 
      "endDate": "2017-07-21T17:17:48.208303"
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "pending", 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-07-23T17:17:48.184527+03:00", 
          "endDate": "2016-07-26T17:17:48.184527+03:00"
        }, 
        "id": "93b5e35b0ece40b88af4114d4c8017fe", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "contractNumber": "contract #13111", 
    "period": {
      "startDate": "2016-07-21T17:17:48.208303+03:00", 
      "endDate": "2017-07-21T17:17:48.208303+03:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateSigned": "2016-07-21T17:18:09.033539+03:00", 
    "date": "2016-07-21T17:18:08.600240+03:00", 
    "awardID": "4d6c14e4bf39434cb637a431367fa9ad", 
    "id": "7806df6a0ceb42cc9c7fff929ed03024", 
    "contractID": "UA-2016-07-21-000001-1"
  }
}

