$ http http://api-sandbox.openprocurement.org/api/0/tenders/b65397298b2e4d9b987adf576d13b9f5/documents
GET /api/0/tenders/b65397298b2e4d9b987adf576d13b9f5/documents HTTP/1.1



HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{
    "data": [
        {
            "datePublished": "2014-11-08T00:09:32.514615", 
            "format": "text/plain", 
            "id": "bab5d3c784314800aee9aa7c0b01730c", 
            "modified": "2014-11-08T00:09:32.514648", 
            "title": "Notice.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/0/tenders/b65397298b2e4d9b987adf576d13b9f5/documents/bab5d3c784314800aee9aa7c0b01730c?download=e0061dc88a16413c805aa14f84554dfc"
        }
    ]
}
