PATCH /api/2.0/tenders/befb9d3f7d284391a71619c9f5681d04/documents/176070a3d2364a5f945421c919f9c4b7?acc_token=4da834b414ca4cc59f88625f8af79aa3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 53
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "documentType": "technicalSpecifications"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "title": "Notice.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/befb9d3f7d284391a71619c9f5681d04/documents/176070a3d2364a5f945421c919f9c4b7?download=4f3db188522f45f08f42566c5e4cfe4b", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-03-16T12:11:43.732197+02:00", 
    "documentType": "technicalSpecifications", 
    "id": "176070a3d2364a5f945421c919f9c4b7", 
    "dateModified": "2016-03-16T12:11:43.732235+02:00"
  }
}

