PATCH /api/2.3/tenders/44c7f9d034dd48629bee829830d084ec/contracts/fa6a13ecfa434c87af90afa3e13a4c09?acc_token=fa100b2f961a46b79f166acd90e1b4bc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 73
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "contractNumber": "contract #13111", 
    "value": {
      "amount": 238
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "pending", 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-07-27T17:49:15.508651+03:00", 
          "endDate": "2017-07-30T17:49:15.508651+03:00"
        }, 
        "id": "d3e749c485954231b9ef3e7951933d5b", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "contractNumber": "contract #13111", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-07-25T17:49:23.684735+03:00", 
    "awardID": "9f3fa995a36c49d298a8c52c170b578f", 
    "id": "fa6a13ecfa434c87af90afa3e13a4c09", 
    "contractID": "UA-2017-07-25-000001-1"
  }
}

