GET /api/2.0/tenders/b75d5f63bf2e42afa5909b1010b04a82/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "description": "document description modified", 
      "title": "Notice.pdf", 
      "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/b75d5f63bf2e42afa5909b1010b04a82/documents/49978259362449ae89950eaa519e130b?download=0683f56f94c741c9a6efe94a6411290b", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-03-16T11:22:29.696178+02:00", 
      "documentType": "technicalSpecifications", 
      "id": "49978259362449ae89950eaa519e130b", 
      "dateModified": "2016-03-16T11:22:29.696217+02:00"
    }, 
    {
      "title": "AwardCriteria.pdf", 
      "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/b75d5f63bf2e42afa5909b1010b04a82/documents/2e541d68445a415bb46767fe9fb8a671?download=ace205435bcf4d758687b7da1eedb9df", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-03-16T11:22:30.284460+02:00", 
      "id": "2e541d68445a415bb46767fe9fb8a671", 
      "dateModified": "2016-03-16T11:22:30.284495+02:00"
    }
  ]
}

