GET /api/2.3/tenders/a4f89b85bdc041f080c73ca5b06ee953/documents/6d900d7c8e584ff99c734991cfbb7137 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "title": "Notice.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/a4f89b85bdc041f080c73ca5b06ee953/documents/6d900d7c8e584ff99c734991cfbb7137?download=e498e2079def4c68b93b7f08cbb62743", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-06-10T15:29:49.569824+03:00", 
    "previousVersions": [], 
    "id": "6d900d7c8e584ff99c734991cfbb7137", 
    "dateModified": "2016-06-10T15:29:49.569872+03:00"
  }
}

