PATCH /api/0.12/tenders/86c2e9f4706041e2abbf98d6662d3c66/contracts/0ff05393466f4690afad476f082f84e6?acc_token=a065886580d7451c9a6bcb13714c0a12 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "title": "contract_first_document.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/86c2e9f4706041e2abbf98d6662d3c66/contracts/0ff05393466f4690afad476f082f84e6/documents/23582c446a0445c08fd6d31913268c9e?download=154f2719953b491fb2b311cf1aa0fabf", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2016-03-18T15:00:38.252166+02:00", 
        "id": "23582c446a0445c08fd6d31913268c9e", 
        "dateModified": "2016-03-18T15:00:38.252215+02:00"
      }, 
      {
        "title": "contract_second_document.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/86c2e9f4706041e2abbf98d6662d3c66/contracts/0ff05393466f4690afad476f082f84e6/documents/f5e0c079e12c448da2399a24ad97e6f8?download=dbf9cad3ae7b46e1a958349e761203ff", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2016-03-18T15:00:38.509656+02:00", 
        "id": "f5e0c079e12c448da2399a24ad97e6f8", 
        "dateModified": "2016-03-18T15:00:38.509694+02:00"
      }
    ], 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "id": "75b294c8c61a4d42a2bb160e6b2915ea", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "period": {
      "startDate": "2016-03-18T15:00:14.568898+02:00", 
      "endDate": "2017-03-18T15:00:14.568898+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateSigned": "2016-03-18T15:00:37.760242+02:00", 
    "awardID": "5906770a3b2f41a0b6c7d15134095ebd", 
    "id": "0ff05393466f4690afad476f082f84e6", 
    "contractID": "UA-2016-03-18-000001-1"
  }
}

