POST /api/2.3/tenders/739500f065ae48a2803388f9b10d3e6e/contracts/1f1c38d99a2543248d1660d7d42367ba/documents?acc_token=6a42c69b4d5849aeaa171f6119fb1b9c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 344
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/0883a3ac1a1c496a8ed2ef7bc71e26e2?KeyID=0eb4ace4&Signature=QcR45Pmp5oDWIIOlMDDJds7Af5bfZKlesaTkaodVyF28weYUFtTE3VgMBYAsiAFqYo37tOdIZHjG8kf7U5%2BjAQ%3D%3D", 
    "title": "contract_first_document.doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/739500f065ae48a2803388f9b10d3e6e/contracts/1f1c38d99a2543248d1660d7d42367ba/documents/f75f71f023a74e65b5bdd2e007cc65dd

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "contract_first_document.doc", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/0883a3ac1a1c496a8ed2ef7bc71e26e2?KeyID=0eb4ace4&Signature=P1CyovDryULMIB9MN268e2%2Fiq1oGhPGNZC%2FD6zXmOhnR4P4dbRbs0dGJTrifyHBQUfH4w1NgIPHlKm%2FrtjeWBTAAAAA4AAAAOAAAADMAAABhAAAAMwAAAGEAAABjAAAA", 
    "format": "application/msword", 
    "documentOf": "tender", 
    "datePublished": "2016-07-21T17:14:53.777829+03:00", 
    "id": "f75f71f023a74e65b5bdd2e007cc65dd", 
    "dateModified": "2016-07-21T17:14:53.777859+03:00"
  }
}

