GET /api/2.3/tenders/44c7f9d034dd48629bee829830d084ec/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description modified", 
      "title": "Notice.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/53e169e286a849f4b4c06412c73fd57f?KeyID=49dd14eb&Signature=zEHTRVdp80Nz1KHqFMZm%252BijjV%252Bx2kdhlFe%252BbNH8JJv4lYm79iUHY%252BbPYROAkFfOmtTd08YKbVHRlLgMo7xhSCQ%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-07-25T17:49:22.822083+03:00", 
      "author": "tender_owner", 
      "documentType": "technicalSpecifications", 
      "id": "2e3f51f16e424cc6aaabb17d9770f446", 
      "dateModified": "2017-07-25T17:49:22.822106+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "AwardCriteria-2.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/6d1826a138bc4fb29f3bc7aa1023e6ca?KeyID=49dd14eb&Signature=uN2gro8zQZX%252BeYRAtswFMtPwR2eHhVgVlwZCr8JwpBd%252BBxiTKZns5uWLr6e094q5It3SIxCXFno%252BTZc2tqBBAQ%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-07-25T17:49:22.910524+03:00", 
      "id": "d087bd91bfb8476b919015c01f3f5e28", 
      "dateModified": "2017-07-25T17:49:22.950692+03:00"
    }
  ]
}

