GET /api/2.3/tenders/3302890835e145a28b553588bc630590/contracts/41970750009b4edabccc5950148ddcee/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "00000000000000000000000000000000", 
      "title": "contract_first_document.doc", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/e8516bdd05c34a9c9a7d3a36cf11e820?KeyID=1a692c8c&Signature=FAfldow6YGY9QPEJ2oarOPU3hbEyG1Py6VqcuoAQWtWGykiV1rGYDdmHlO2Eg3qLWiZr8yEDAyVp49M76OjGAWUAAAA4AAAANQAAADEAAAA2AAAAYgAAAGQAAABkAAAA", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2016-07-20T17:17:37.632015+03:00", 
      "id": "7fada6f7c177406480bcbec3cd4abb0a", 
      "dateModified": "2016-07-20T17:17:37.632049+03:00"
    }
  ]
}

