PATCH /api/2.3/tenders/8719bac9dfde46d687952023d139e04b?acc_token=8aadcddcf7f44a4b97e99df7bc53cb67 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active.enquiries"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "status": "active.enquiries", 
    "awardCriteria": "lowestCost", 
    "tenderPeriod": {
      "startDate": "2017-07-01T18:00:25.084270+03:00", 
      "endDate": "2017-07-08T18:00:25.084270+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-06-26T18:00:25.084270+03:00", 
          "endDate": "2017-06-29T18:00:25.084270+03:00"
        }, 
        "id": "c2434e5db0cf47ce8391b405dbbde5c7", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "procurementMethodType": "belowThreshold", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2017-06-24T18:00:26.520341+03:00", 
    "next_check": "2017-07-01T18:00:25.084270+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "enquiryPeriod": {
      "startDate": "2017-06-24T18:00:26.459987+03:00", 
      "endDate": "2017-07-01T18:00:25.084270+03:00"
    }, 
    "owner": "broker", 
    "dateModified": "2017-06-24T18:00:26.520341+03:00", 
    "id": "8719bac9dfde46d687952023d139e04b", 
    "tenderID": "UA-2017-06-24-000001"
  }
}

