PATCH /api/2.3/tenders/ff9d7e23ff5b40bba2818f427c9c4811?acc_token=77f642c025a143008742c04d57135a5a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active.enquiries"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "status": "active.enquiries", 
    "tenderID": "UA-2016-05-12-000001", 
    "tenderPeriod": {
      "startDate": "2016-05-19T18:07:59.549219+03:00", 
      "endDate": "2016-05-26T18:07:59.549219+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-05-14T18:07:59.549219+03:00", 
          "endDate": "2016-05-17T18:07:59.549219+03:00"
        }, 
        "id": "35c948dc2d1d45d2b72d40992ce5e110", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "procurementMethodType": "belowThreshold", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2016-05-19T18:07:59.549219+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "enquiryPeriod": {
      "startDate": "2016-05-12T18:08:00.805651+03:00", 
      "endDate": "2016-05-19T18:07:59.549219+03:00"
    }, 
    "owner": "broker", 
    "dateModified": "2016-05-12T18:08:00.954938+03:00", 
    "id": "ff9d7e23ff5b40bba2818f427c9c4811", 
    "awardCriteria": "lowestCost"
  }
}

