GET /api/2.3/tenders/3d59d3514f8d44cbbc946731d71c69e2/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description modified", 
      "title": "Notice.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/fe0493de2ed24f35ac9058c79cdc8a6f?KeyID=ad57153b&Signature=IasRqcTaPBkyhJnMIVVCmfB%252BA5URnkAtT%2F5dYP9jquEQ4Z64lYgEx5ladvryMojPkefIczLCI8LJn6vUQ1hFAA%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-06-19T18:27:54.908542+03:00", 
      "documentType": "technicalSpecifications", 
      "id": "992b97063a26419c80caf6e4471ffa17", 
      "dateModified": "2017-06-19T18:27:54.908584+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "AwardCriteria-2.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/1371bfc814fe41deb186482e65985cac?KeyID=ad57153b&Signature=S4OLpkCasSEXNUkHqbcIRjQetTX27lzzRFLaV9FRBj0FMsLJshvqTZCydnJsny3cmQkdiI%2Fn26nc2XE3168IAg%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-06-19T18:27:55.110662+03:00", 
      "id": "4f84a7eba14f4957bc4e3dd0ef719a9f", 
      "dateModified": "2017-06-19T18:27:55.189257+03:00"
    }
  ]
}

