PATCH /api/2.3/tenders/44c7f9d034dd48629bee829830d084ec/contracts/fa6a13ecfa434c87af90afa3e13a4c09?acc_token=fa100b2f961a46b79f166acd90e1b4bc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 60
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "dateSigned": "2017-07-25T17:49:24.230728+03:00"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_first_document.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/3d1ee2c4045e4eeaa2b8d7fe2aec48e3?KeyID=49dd14eb&Signature=2WDw5hrx8l0Pk8Kpcmp5e%2Fpa0Nl5Hz9ExGxO2FNobSldFsgDEyGSM1hL%2FAObRpdgDWIQZqqy9FGmR%252BLeyMB5BQ%253D%253D", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2017-07-25T17:49:24.056973+03:00", 
        "id": "b9cbff9ae6a24bbb9c1cb80dc532765c", 
        "dateModified": "2017-07-25T17:49:24.056992+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_second_document.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/8f69ec3fc751456e89b02e1b73b5202a?KeyID=49dd14eb&Signature=PZoQ%2Fom8ZRWzUpbIt7tYAJvxMxd9rQ9Qvk6zuj9ZYMbx21LO74cAddVl1NjWzLfO7YDTEhhyFGSAxRFi18leBQ%253D%253D", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2017-07-25T17:49:24.156066+03:00", 
        "id": "a719e6e4c4154b1ab637f220e412b636", 
        "dateModified": "2017-07-25T17:49:24.156084+03:00"
      }
    ], 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-07-27T17:49:15.508651+03:00", 
          "endDate": "2017-07-30T17:49:15.508651+03:00"
        }, 
        "id": "d3e749c485954231b9ef3e7951933d5b", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "contractNumber": "contract #13111", 
    "period": {
      "startDate": "2017-07-25T17:49:15.526165+03:00", 
      "endDate": "2018-07-25T17:49:15.526165+03:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateSigned": "2017-07-25T17:49:24.230728+03:00", 
    "date": "2017-07-25T17:49:23.684735+03:00", 
    "awardID": "9f3fa995a36c49d298a8c52c170b578f", 
    "id": "fa6a13ecfa434c87af90afa3e13a4c09", 
    "contractID": "UA-2017-07-25-000001-1"
  }
}

