PATCH /api/2.3/tenders/44c7f9d034dd48629bee829830d084ec/documents/2e3f51f16e424cc6aaabb17d9770f446?acc_token=fa100b2f961a46b79f166acd90e1b4bc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 53
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "documentType": "technicalSpecifications"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/53e169e286a849f4b4c06412c73fd57f?KeyID=49dd14eb&Signature=zEHTRVdp80Nz1KHqFMZm%252BijjV%252Bx2kdhlFe%252BbNH8JJv4lYm79iUHY%252BbPYROAkFfOmtTd08YKbVHRlLgMo7xhSCQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-07-25T17:49:22.822083+03:00", 
    "documentType": "technicalSpecifications", 
    "id": "2e3f51f16e424cc6aaabb17d9770f446", 
    "dateModified": "2017-07-25T17:49:22.822106+03:00"
  }
}

