PATCH /api/2.3/tenders/a4f89b85bdc041f080c73ca5b06ee953/documents/6d900d7c8e584ff99c734991cfbb7137?acc_token=be391cdea4bf4d04b9794dc15d5f4b41 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 58
Content-Type: application/json
Host: public.api.openprocurement.org

{
  "data": {
    "description": "document description modified"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "description": "document description modified", 
    "title": "Notice.pdf", 
    "url": "https://public.api.openprocurement.org/api/2.3/tenders/a4f89b85bdc041f080c73ca5b06ee953/documents/6d900d7c8e584ff99c734991cfbb7137?download=e498e2079def4c68b93b7f08cbb62743", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-06-10T15:29:49.569824+03:00", 
    "documentType": "technicalSpecifications", 
    "id": "6d900d7c8e584ff99c734991cfbb7137", 
    "dateModified": "2016-06-10T15:29:49.569872+03:00"
  }
}

