PATCH /api/2.3/tenders/3302890835e145a28b553588bc630590/contracts/41970750009b4edabccc5950148ddcee?acc_token=33c91d872a85435089b156e3fc93edb6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 73
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "contractNumber": "contract #13111", 
    "value": {
      "amount": 238
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "pending", 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-07-22T17:17:15.566684+03:00", 
          "endDate": "2016-07-25T17:17:15.566684+03:00"
        }, 
        "id": "624c3265559f4fbc946ce6dbd72181a5", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "contractNumber": "contract #13111", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-07-20T17:17:36.983372+03:00", 
    "awardID": "7afd8fb0a1ce4d249219c632dcfaaffc", 
    "id": "41970750009b4edabccc5950148ddcee", 
    "contractID": "UA-2016-07-20-000001-1"
  }
}

