GET /api/0.12/tenders/d43c874272844fab88e7f2681b304252/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "description": "document description modified", 
      "title": "Notice.pdf", 
      "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/d43c874272844fab88e7f2681b304252/documents/5730009672ce4beab262362b2ac39ad1?download=4f8d0fc0d9424cb58fa99e9ac453e7fa", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-03-14T21:29:08.933077+02:00", 
      "documentType": "technicalSpecifications", 
      "id": "5730009672ce4beab262362b2ac39ad1", 
      "dateModified": "2016-03-14T21:29:08.933118+02:00"
    }, 
    {
      "title": "AwardCriteria.pdf", 
      "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/d43c874272844fab88e7f2681b304252/documents/60a0090c199449d4b0c758985a5ffc4f?download=bb88b9e645b34118aafbd4d2c935770e", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-03-14T21:29:09.363798+02:00", 
      "id": "60a0090c199449d4b0c758985a5ffc4f", 
      "dateModified": "2016-03-14T21:29:09.363842+02:00"
    }
  ]
}

