GET /api/0.12/tenders/967afe7b23914929a9be803df29381ef/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "title": "Notice.pdf", 
      "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/967afe7b23914929a9be803df29381ef/documents/29f3c1a2b049462d9be4ec8a9bcee6fe?download=f70e2d4f5eff4b6f990f2e91073acc58", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-02-01T12:18:03.767900+02:00", 
      "id": "29f3c1a2b049462d9be4ec8a9bcee6fe", 
      "dateModified": "2016-02-01T12:18:03.767943+02:00"
    }, 
    {
      "title": "AwardCriteria.pdf", 
      "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/967afe7b23914929a9be803df29381ef/documents/f6e58f2698ec4c04a5b8cec403fac1cb?download=c441c0857bc847ee89eb861e378e77f4", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2016-02-01T12:18:03.937206+02:00", 
      "id": "f6e58f2698ec4c04a5b8cec403fac1cb", 
      "dateModified": "2016-02-01T12:18:03.937237+02:00"
    }
  ]
}

