PATCH /api/0.12/tenders/ce536c5f46d543ec81ffa86ce4c77c8b/documents/caeb63b8bee24a3cbf4d7f8bbbe7352b?acc_token=945a452ee1b442bdaf665b09d0cb4cce HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 58
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "description": "document description modified"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "description": "document description modified", 
    "title": "Notice.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/ce536c5f46d543ec81ffa86ce4c77c8b/documents/caeb63b8bee24a3cbf4d7f8bbbe7352b?download=f7a875fc152744c7a5e9124a400f688a", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-03-18T18:48:02.645660+02:00", 
    "documentType": "technicalSpecifications", 
    "id": "caeb63b8bee24a3cbf4d7f8bbbe7352b", 
    "dateModified": "2016-03-18T18:48:02.645712+02:00"
  }
}

