PATCH /api/2.3/tenders/739500f065ae48a2803388f9b10d3e6e/contracts/1f1c38d99a2543248d1660d7d42367ba?acc_token=6a42c69b4d5849aeaa171f6119fb1b9c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 106
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "period": {
      "startDate": "2016-07-21T17:14:32.683716", 
      "endDate": "2017-07-21T17:14:32.683716"
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "pending", 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2016-07-23T17:14:32.682336+03:00", 
          "endDate": "2016-07-26T17:14:32.682336+03:00"
        }, 
        "id": "e5750f26ed7145fbaf0d9db217998658", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "contractNumber": "contract #13111", 
    "period": {
      "startDate": "2016-07-21T17:14:32.683716+03:00", 
      "endDate": "2017-07-21T17:14:32.683716+03:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateSigned": "2016-07-21T17:14:53.242075+03:00", 
    "date": "2016-07-21T17:14:53.588463+03:00", 
    "awardID": "0f8c888b8959477aa791bb637a53f67f", 
    "id": "1f1c38d99a2543248d1660d7d42367ba", 
    "contractID": "UA-2016-07-21-000001-1"
  }
}

