PATCH /api/0.12/tenders/c734b0da0d05467a82ae248b319b79e1/contracts/8a3f870ab3b941fb9e656a4e18ba26da?acc_token=45f71956f89b48eea8ca964dd4bf97fb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 106
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "period": {
      "startDate": "2016-03-16T15:13:00.799773", 
      "endDate": "2017-03-16T15:13:00.799773"
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "pending", 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "id": "8655bb55172f4ca4b9733b90f919180c", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "period": {
      "startDate": "2016-03-16T15:13:00.799773+02:00", 
      "endDate": "2017-03-16T15:13:00.799773+02:00"
    }, 
    "dateSigned": "2016-03-16T15:13:26.581305+02:00", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardID": "5f86ddc49b6c4d7da042b4a8fbb9ad6b", 
    "id": "8a3f870ab3b941fb9e656a4e18ba26da", 
    "contractID": "UA-2016-03-16-000001-1"
  }
}

