PATCH /api/0.12/tenders/e98e2eb727c645d4b04ff7a56fef272f/documents/581e56fb95814c7abf5740e8414542ca?acc_token=fb616747193c4f9bba0aee4e40c29121 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 58
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "description": "document description modified"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "description": "document description modified", 
    "title": "Notice.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/e98e2eb727c645d4b04ff7a56fef272f/documents/581e56fb95814c7abf5740e8414542ca?download=ad74e10468f349ce82b0a47d1f4a3eac", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-02-10T12:41:59.719658+02:00", 
    "documentType": "technicalSpecifications", 
    "id": "581e56fb95814c7abf5740e8414542ca", 
    "dateModified": "2016-02-10T12:41:59.719691+02:00"
  }
}

