PUT /api/2.3/tenders/739500f065ae48a2803388f9b10d3e6e/cancellations/e53e8fb9b6c7421d927ca306efd50a83/documents/e4277d4b72714623b2e7d6ca8b70a292?acc_token=6a42c69b4d5849aeaa171f6119fb1b9c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 330
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/b27ad9d9b1d54be380bf16f635c4adcc?KeyID=0eb4ace4&Signature=oDbFbsUc9tmlP3m%2FrGj4%2BHf9nJWP4V8ZMYegDiH216LZJhSCmvCptCWrtrmp1uPt55SelqIkhnmxu%2BJTwUmQCg%3D%3D", 
    "title": "Notice-2.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "title": "Notice-2.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/b27ad9d9b1d54be380bf16f635c4adcc?KeyID=0eb4ace4&Signature=gjDA7K3UZOF8Cudn4hkZaewQdq%252BjdOElvydCkF%2FtRn%252B95t%2Fsd%2F1q%252BEzFIKzXe8U25zzhXHv9CsJOZHQW52s3DGIAAAAyAAAANwAAAGEAAABkAAAAOQAAAGQAAAA5AAAA", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-07-21T17:14:55.237726+03:00", 
    "id": "e4277d4b72714623b2e7d6ca8b70a292", 
    "dateModified": "2016-07-21T17:14:55.653331+03:00"
  }
}

