PUT /api/0.12/tenders/524bbb240f56473d8fab351c739af804/documents/d5c8f05ac38f4692a6bddcbfccfa0b32?acc_token=7ef98d7212014590bd1182a055c70209 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 196
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy384250040548$
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "title": "AwardCriteria-2.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/524bbb240f56473d8fab351c739af804/documents/d5c8f05ac38f4692a6bddcbfccfa0b32?download=2e66f6a148f4499fb3d5b280cc887a9a", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-02-04T16:00:52.334078+02:00", 
    "id": "d5c8f05ac38f4692a6bddcbfccfa0b32", 
    "dateModified": "2016-02-04T16:00:52.514113+02:00"
  }
}

