POST /api/0.12/tenders/c5cc24b1753140aebf0dfe98297fdd08/documents?acc_token=92fa8b316fe8471e8c5298ad285d9702 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 186
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy885454073103$
Host: api-sandbox.openprocurement.org


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/0.12/tenders/c5cc24b1753140aebf0dfe98297fdd08/documents/3b7eff544d07446ba39c9e7fbd468b53

{
  "data": {
    "title": "Notice.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/0.12/tenders/c5cc24b1753140aebf0dfe98297fdd08/documents/3b7eff544d07446ba39c9e7fbd468b53?download=62e61a23260141b4bd9c5293bafee8bb", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-02-09T18:44:08.940034+02:00", 
    "id": "3b7eff544d07446ba39c9e7fbd468b53", 
    "dateModified": "2016-02-09T18:44:08.940078+02:00"
  }
}

