POST /api/2.3/tenders/e2cec5ad28bd4c3a8fe3364457b0ece8/cancellations/8e0c548aa7174612a3b933019d823fa7/documents?acc_token=9af449b524a647ff9b25b441219a2a7d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 186
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy267025503656$
Host: api-sandbox.openprocurement.org


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/e2cec5ad28bd4c3a8fe3364457b0ece8/cancellations/8e0c548aa7174612a3b933019d823fa7/documents/0db27f40dbb445e29756fbd2a70087bf

{
  "data": {
    "hash": "00000000000000000000000000000000", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/c6ee11210ce6411080d733dd8e15564f?KeyID=f183a4c7&Signature=pJ67o5mrEUqwKIJv%2FitvUBWE%252BFl7vhPINBLnMNqDRpzJMYZMlyfrXwk0GpIHh6%252BvZk%252BeUOD0F2jCJMozfiAKCWMAAAA2AAAAZQAAAGUAAAAxAAAAMQAAADIAAAAxAAAA", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-07-19T16:09:40.517953+03:00", 
    "id": "0db27f40dbb445e29756fbd2a70087bf", 
    "dateModified": "2016-07-19T16:09:40.517994+03:00"
  }
}

