POST /api/2.0/tenders/3bbde406592c4c82b392442cc7affbbc/documents?acc_token=e63fecce92854fc38bb5c3f5d3df15c2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 193
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy464370463202$
Host: api-sandbox.openprocurement.org


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.0/tenders/3bbde406592c4c82b392442cc7affbbc/documents/22d74de08fd340cb86490df9167fbca9

{
  "data": {
    "title": "AwardCriteria.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/3bbde406592c4c82b392442cc7affbbc/documents/22d74de08fd340cb86490df9167fbca9?download=83d8e0201eb44a8f997197a3366c0e70", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-03-16T14:12:01.239911+02:00", 
    "id": "22d74de08fd340cb86490df9167fbca9", 
    "dateModified": "2016-03-16T14:12:01.239947+02:00"
  }
}

