POST /api/2.3/tenders/739500f065ae48a2803388f9b10d3e6e/documents?acc_token=6a42c69b4d5849aeaa171f6119fb1b9c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 333
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/b751b0d7b21e416192bb8edd6c78d621?KeyID=0eb4ace4&Signature=SZitKSLljBDoPFLEK2VmY%2B3PjaZ8zqsY3F5QqVARXurp4XSPIrDGGEvkuVnAHwHRiqFZaOibk%2FIvoFuckfPTAQ%3D%3D", 
    "title": "AwardCriteria.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/739500f065ae48a2803388f9b10d3e6e/documents/d988dacddfc54cf6bb1af71773b8cb16

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "AwardCriteria.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/b751b0d7b21e416192bb8edd6c78d621?KeyID=0eb4ace4&Signature=SWAxlH3q1dgdDfUmeQ%2FODFGN6Qs5wOiBhSnsYWMCZQg6DowhfUZ64Uno9niQ%2FEyeBhkoB3lqcfGJljaOExvGC2IAAAA3AAAANQAAADEAAABiAAAAMAAAAGQAAAA3AAAA", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-07-21T17:14:50.482384+03:00", 
    "id": "d988dacddfc54cf6bb1af71773b8cb16", 
    "dateModified": "2016-07-21T17:14:50.482417+03:00"
  }
}

